#!/bin/bash
# Config file for jellyshot

# shellcheck disable=SC2034
# SERVER='sigfu.tk'
SERVER='alyp.tk'
PORT='222'
# SERVER_PATH='uhr'
SERVER_PATH='/srv/http/uhr'
SUFFIX='uhr'

# Used if no SERVER_PATH
USER=http

