'\" t
.\"     Title: __insert_inode_hash
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: January 2017
.\"    Manual: The Linux VFS
.\"    Source: Kernel Hackers Manual 4.10.0-rc1
.\"  Language: English
.\"
.TH "__INSERT_INODE_HASH" "9" "January 2017" "Kernel Hackers Manual 4\&.10\&" "The Linux VFS"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
__insert_inode_hash \- hash an inode
.SH "SYNOPSIS"
.HP \w'void\ __insert_inode_hash('u
.BI "void __insert_inode_hash(struct\ inode\ *\ " "inode" ", unsigned\ long\ " "hashval" ");"
.SH "ARGUMENTS"
.PP
\fIinode\fR
.RS 4
unhashed inode
.RE
.PP
\fIhashval\fR
.RS 4
unsigned long value used to locate this object in the inode_hashtable\&.
.RE
.SH "DESCRIPTION"
.PP
Add an inode to the inode hash for this superblock\&.
.SH "COPYRIGHT"
.br
