'\" t
.\"     Title: __pskb_pull_tail
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: January 2017
.\"    Manual: Linux Networking
.\"    Source: Kernel Hackers Manual 4.10.0-rc1
.\"  Language: English
.\"
.TH "__PSKB_PULL_TAIL" "9" "January 2017" "Kernel Hackers Manual 4\&.10\&" "Linux Networking"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
__pskb_pull_tail \- advance tail of skb header
.SH "SYNOPSIS"
.HP \w'unsigned\ char\ *\ __pskb_pull_tail('u
.BI "unsigned char * __pskb_pull_tail(struct\ sk_buff\ *\ " "skb" ", int\ " "delta" ");"
.SH "ARGUMENTS"
.PP
\fIskb\fR
.RS 4
buffer to reallocate
.RE
.PP
\fIdelta\fR
.RS 4
number of bytes to advance tail
.RE
.SH "DESCRIPTION"
.PP
The function makes a sense only on a fragmented
sk_buff, it expands header moving its tail forward and copying necessary data from fragmented part\&.
.PP
sk_buff
MUST have reference count of 1\&.
.PP
Returns
\fBNULL\fR
(and
sk_buff
does not change) if pull failed or value of new tail of skb in the case of success\&.
.PP
All the pointers pointing into skb header may change and must be reloaded after call to this function\&.
.SH "COPYRIGHT"
.br
