'\" t
.\"     Title: __sk_mem_raise_allocated
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: January 2017
.\"    Manual: Linux Networking
.\"    Source: Kernel Hackers Manual 4.10.0-rc1
.\"  Language: English
.\"
.TH "__SK_MEM_RAISE_ALLOC" "9" "January 2017" "Kernel Hackers Manual 4\&.10\&" "Linux Networking"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
__sk_mem_raise_allocated \- increase memory_allocated
.SH "SYNOPSIS"
.HP \w'int\ __sk_mem_raise_allocated('u
.BI "int __sk_mem_raise_allocated(struct\ sock\ *\ " "sk" ", int\ " "size" ", int\ " "amt" ", int\ " "kind" ");"
.SH "ARGUMENTS"
.PP
\fIsk\fR
.RS 4
socket
.RE
.PP
\fIsize\fR
.RS 4
memory size to allocate
.RE
.PP
\fIamt\fR
.RS 4
pages to allocate
.RE
.PP
\fIkind\fR
.RS 4
allocation type
.RE
.SH "DESCRIPTION"
.PP
Similar to
\fB__sk_mem_schedule\fR, but does not update sk_forward_alloc
.SH "COPYRIGHT"
.br
