'\" t
.\"     Title: audit_log_format
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: January 2017
.\"    Manual: Audit Interfaces
.\"    Source: Kernel Hackers Manual 4.10.0-rc1
.\"  Language: English
.\"
.TH "AUDIT_LOG_FORMAT" "9" "January 2017" "Kernel Hackers Manual 4\&.10\&" "Audit Interfaces"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
audit_log_format \- format a message into the audit buffer\&.
.SH "SYNOPSIS"
.HP \w'void\ audit_log_format('u
.BI "void audit_log_format(struct\ audit_buffer\ *\ " "ab" ", const\ char\ *\ " "fmt" ", " "\&.\&.\&." ");"
.SH "ARGUMENTS"
.PP
\fIab\fR
.RS 4
audit_buffer
.RE
.PP
\fIfmt\fR
.RS 4
format string
.RE
.PP
\fI\&.\&.\&.\fR
.RS 4
optional parameters matching
\fIfmt\fR
string
.RE
.SH "DESCRIPTION"
.PP
All the work is done in audit_log_vformat\&.
.SH "COPYRIGHT"
.br
