'\" t
.\"     Title: d_obtain_alias
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: January 2017
.\"    Manual: The Linux VFS
.\"    Source: Kernel Hackers Manual 4.10.0-rc1
.\"  Language: English
.\"
.TH "D_OBTAIN_ALIAS" "9" "January 2017" "Kernel Hackers Manual 4\&.10\&" "The Linux VFS"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
d_obtain_alias \- find or allocate a DISCONNECTED dentry for a given inode
.SH "SYNOPSIS"
.HP \w'struct\ dentry\ *\ d_obtain_alias('u
.BI "struct dentry * d_obtain_alias(struct\ inode\ *\ " "inode" ");"
.SH "ARGUMENTS"
.PP
\fIinode\fR
.RS 4
inode to allocate the dentry for
.RE
.SH "DESCRIPTION"
.PP
Obtain a dentry for an inode resulting from NFS filehandle conversion or similar open by handle operations\&. The returned dentry may be anonymous, or may have a full name (if the inode was already in the cache)\&.
.PP
When called on a directory inode, we must ensure that the inode only ever has one dentry\&. If a dentry is found, that is returned instead of allocating a new one\&.
.PP
On successful return, the reference to the inode has been transferred to the dentry\&. In case of an error the reference on the inode is released\&. To make it easier to use in export operations a
\fBNULL\fR
or IS_ERR inode may be passed in and the error will be propagated to the return value, with a
\fBNULL\fR
\fIinode\fR
replaced by ERR_PTR(\-ESTALE)\&.
.SH "COPYRIGHT"
.br
