'\" t
.\"     Title: dev_set_mac_address
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: January 2017
.\"    Manual: Network device support
.\"    Source: Kernel Hackers Manual 4.10.0-rc1
.\"  Language: English
.\"
.TH "DEV_SET_MAC_ADDRESS" "9" "January 2017" "Kernel Hackers Manual 4\&.10\&" "Network device support"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
dev_set_mac_address \- Change Media Access Control Address
.SH "SYNOPSIS"
.HP \w'int\ dev_set_mac_address('u
.BI "int dev_set_mac_address(struct\ net_device\ *\ " "dev" ", struct\ sockaddr\ *\ " "sa" ");"
.SH "ARGUMENTS"
.PP
\fIdev\fR
.RS 4
device
.RE
.PP
\fIsa\fR
.RS 4
new address
.RE
.SH "DESCRIPTION"
.PP
Change the hardware (MAC) address of the device
.SH "COPYRIGHT"
.br
