'\" t
.\"     Title: dget_dlock
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: January 2017
.\"    Manual: The Linux VFS
.\"    Source: Kernel Hackers Manual 4.10.0-rc1
.\"  Language: English
.\"
.TH "DGET_DLOCK" "9" "January 2017" "Kernel Hackers Manual 4\&.10\&" "The Linux VFS"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
dget_dlock \- get a reference to a dentry
.SH "SYNOPSIS"
.HP \w'struct\ dentry\ *\ dget_dlock('u
.BI "struct dentry * dget_dlock(struct\ dentry\ *\ " "dentry" ");"
.SH "ARGUMENTS"
.PP
\fIdentry\fR
.RS 4
dentry to get a reference to
.RE
.SH "DESCRIPTION"
.PP
Given a dentry or
\fBNULL\fR
pointer increment the reference count if appropriate and return the dentry\&. A dentry will not be destroyed when it has references\&.
.SH "COPYRIGHT"
.br
