'\" t
.\"     Title: dmi_first_match
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: January 2017
.\"    Manual: Firmware Interfaces
.\"    Source: Kernel Hackers Manual 4.10.0-rc1
.\"  Language: English
.\"
.TH "DMI_FIRST_MATCH" "9" "January 2017" "Kernel Hackers Manual 4\&.10\&" "Firmware Interfaces"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
dmi_first_match \- find dmi_system_id structure matching system DMI data
.SH "SYNOPSIS"
.HP \w'const\ struct\ dmi_system_id\ *\ dmi_first_match('u
.BI "const struct dmi_system_id * dmi_first_match(const\ struct\ dmi_system_id\ *\ " "list" ");"
.SH "ARGUMENTS"
.PP
\fIlist\fR
.RS 4
array of dmi_system_id structures to match against All non\-null elements of the list must match their slot\*(Aqs (field index\*(Aqs) data (i\&.e\&., each list string must be a substring of the specified DMI slot\*(Aqs string data) to be considered a successful match\&.
.RE
.SH "DESCRIPTION"
.PP
Walk the blacklist table until the first match is found\&. Return the pointer to the matching entry or NULL if there\*(Aqs no match\&.
.SH "COPYRIGHT"
.br
