'\" t
.\"     Title: enum netdev_priv_flags
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: January 2017
.\"    Manual: Network device support
.\"    Source: Kernel Hackers Manual 4.10.0-rc1
.\"  Language: English
.\"
.TH "ENUM NETDEV_PRIV_FLA" "9" "January 2017" "Kernel Hackers Manual 4\&.10\&" "Network device support"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
enum_netdev_priv_flags \- struct net_device priv_flags
.SH "SYNOPSIS"
.sp
.nf
enum netdev_priv_flags {
  IFF_802_1Q_VLAN,
  IFF_EBRIDGE,
  IFF_BONDING,
  IFF_ISATAP,
  IFF_WAN_HDLC,
  IFF_XMIT_DST_RELEASE,
  IFF_DONT_BRIDGE,
  IFF_DISABLE_NETPOLL,
  IFF_MACVLAN_PORT,
  IFF_BRIDGE_PORT,
  IFF_OVS_DATAPATH,
  IFF_TX_SKB_SHARING,
  IFF_UNICAST_FLT,
  IFF_TEAM_PORT,
  IFF_SUPP_NOFCS,
  IFF_LIVE_ADDR_CHANGE,
  IFF_MACVLAN,
  IFF_XMIT_DST_RELEASE_PERM,
  IFF_IPVLAN_MASTER,
  IFF_IPVLAN_SLAVE,
  IFF_L3MDEV_MASTER,
  IFF_NO_QUEUE,
  IFF_OPENVSWITCH,
  IFF_L3MDEV_SLAVE,
  IFF_TEAM,
  IFF_RXFH_CONFIGURED,
  IFF_PHONY_HEADROOM,
  IFF_MACSEC
};  
.fi
.SH "CONSTANTS"
.PP
IFF_802_1Q_VLAN
.RS 4
802\&.1Q VLAN device
.RE
.PP
IFF_EBRIDGE
.RS 4
Ethernet bridging device
.RE
.PP
IFF_BONDING
.RS 4
bonding master or slave
.RE
.PP
IFF_ISATAP
.RS 4
ISATAP interface (RFC4214)
.RE
.PP
IFF_WAN_HDLC
.RS 4
WAN HDLC device
.RE
.PP
IFF_XMIT_DST_RELEASE
.RS 4
\fBdev_hard_start_xmit\fR
is allowed to release skb\->dst
.RE
.PP
IFF_DONT_BRIDGE
.RS 4
disallow bridging this ether dev
.RE
.PP
IFF_DISABLE_NETPOLL
.RS 4
disable netpoll at run\-time
.RE
.PP
IFF_MACVLAN_PORT
.RS 4
device used as macvlan port
.RE
.PP
IFF_BRIDGE_PORT
.RS 4
device used as bridge port
.RE
.PP
IFF_OVS_DATAPATH
.RS 4
device used as Open vSwitch datapath port
.RE
.PP
IFF_TX_SKB_SHARING
.RS 4
The interface supports sharing skbs on transmit
.RE
.PP
IFF_UNICAST_FLT
.RS 4
Supports unicast filtering
.RE
.PP
IFF_TEAM_PORT
.RS 4
device used as team port
.RE
.PP
IFF_SUPP_NOFCS
.RS 4
device supports sending custom FCS
.RE
.PP
IFF_LIVE_ADDR_CHANGE
.RS 4
device supports hardware address change when it\*(Aqs running
.RE
.PP
IFF_MACVLAN
.RS 4
Macvlan device
.RE
.PP
IFF_XMIT_DST_RELEASE_PERM
.RS 4
IFF_XMIT_DST_RELEASE not taking into account underlying stacked devices
.RE
.PP
IFF_IPVLAN_MASTER
.RS 4
IPvlan master device
.RE
.PP
IFF_IPVLAN_SLAVE
.RS 4
IPvlan slave device
.RE
.PP
IFF_L3MDEV_MASTER
.RS 4
device is an L3 master device
.RE
.PP
IFF_NO_QUEUE
.RS 4
device can run without qdisc attached
.RE
.PP
IFF_OPENVSWITCH
.RS 4
device is a Open vSwitch master
.RE
.PP
IFF_L3MDEV_SLAVE
.RS 4
device is enslaved to an L3 master device
.RE
.PP
IFF_TEAM
.RS 4
device is a team device
.RE
.PP
IFF_RXFH_CONFIGURED
.RS 4
device has had Rx Flow indirection table configured
.RE
.PP
IFF_PHONY_HEADROOM
.RS 4
the headroom value is controlled by an external entity (i\&.e\&. the master device for bridged veth)
.RE
.PP
IFF_MACSEC
.RS 4
device is a MACsec device
.RE
.SH "DESCRIPTION"
.PP
.PP
These are the
struct net_device, they are only set internally by drivers and used in the kernel\&. These flags are invisible to userspace; this means that the order of these flags can change during any kernel release\&.
.PP
You should have a pretty good reason to be extending these flags\&.
.SH "COPYRIGHT"
.br
