'\" t
.\"     Title: fc_vport_create
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: January 2017
.\"    Manual: SCSI mid layer
.\"    Source: Kernel Hackers Manual 4.10.0-rc1
.\"  Language: English
.\"
.TH "FC_VPORT_CREATE" "9" "January 2017" "Kernel Hackers Manual 4\&.10\&" "SCSI mid layer"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
fc_vport_create \- Admin App or LLDD requests creation of a vport
.SH "SYNOPSIS"
.HP \w'struct\ fc_vport\ *\ fc_vport_create('u
.BI "struct fc_vport * fc_vport_create(struct\ Scsi_Host\ *\ " "shost" ", int\ " "channel" ", struct\ fc_vport_identifiers\ *\ " "ids" ");"
.SH "ARGUMENTS"
.PP
\fIshost\fR
.RS 4
scsi host the virtual port is connected to\&.
.RE
.PP
\fIchannel\fR
.RS 4
channel on shost port connected to\&.
.RE
.PP
\fIids\fR
.RS 4
The world wide names, FC4 port roles, etc for the virtual port\&.
.RE
.SH "NOTES"
.PP
This routine assumes no locks are held on entry\&.
.SH "AUTHORS"
.PP
\fBJames Bottomley\fR <\&James.Bottomley@hansenpartnership.com\&>
.RS 4
Author.
.RE
.PP
\fBRob Landley\fR <\&rob@landley.net\&>
.RS 4
Author.
.RE
.SH "COPYRIGHT"
.br
