'\" t
.\"     Title: get_pfn_range_for_nid
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: January 2017
.\"    Manual: Memory Management in Linux
.\"    Source: Kernel Hackers Manual 4.10.0-rc1
.\"  Language: English
.\"
.TH "GET_PFN_RANGE_FOR_NI" "9" "January 2017" "Kernel Hackers Manual 4\&.10\&" "Memory Management in Linux"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
get_pfn_range_for_nid \- Return the start and end page frames for a node
.SH "SYNOPSIS"
.HP \w'void\ get_pfn_range_for_nid('u
.BI "void get_pfn_range_for_nid(unsigned\ int\ " "nid" ", unsigned\ long\ *\ " "start_pfn" ", unsigned\ long\ *\ " "end_pfn" ");"
.SH "ARGUMENTS"
.PP
\fInid\fR
.RS 4
The nid to return the range for\&. If MAX_NUMNODES, the min and max PFN are returned\&.
.RE
.PP
\fIstart_pfn\fR
.RS 4
Passed by reference\&. On return, it will have the node start_pfn\&.
.RE
.PP
\fIend_pfn\fR
.RS 4
Passed by reference\&. On return, it will have the node end_pfn\&.
.RE
.SH "DESCRIPTION"
.PP
It returns the start and end page frame of a node based on information provided by
\fBmemblock_set_node\fR\&. If called for a node with no available memory, a warning is printed and the start and end PFNs will be 0\&.
.SH "COPYRIGHT"
.br
