'\" t
.\"     Title: ilookup
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: January 2017
.\"    Manual: The Linux VFS
.\"    Source: Kernel Hackers Manual 4.10.0-rc1
.\"  Language: English
.\"
.TH "ILOOKUP" "9" "January 2017" "Kernel Hackers Manual 4\&.10\&" "The Linux VFS"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
ilookup \- search for an inode in the inode cache
.SH "SYNOPSIS"
.HP \w'struct\ inode\ *\ ilookup('u
.BI "struct inode * ilookup(struct\ super_block\ *\ " "sb" ", unsigned\ long\ " "ino" ");"
.SH "ARGUMENTS"
.PP
\fIsb\fR
.RS 4
super block of file system to search
.RE
.PP
\fIino\fR
.RS 4
inode number to search for
.RE
.SH "DESCRIPTION"
.PP
Search for the inode
\fIino\fR
in the inode cache, and if the inode is in the cache, the inode is returned with an incremented reference count\&.
.SH "COPYRIGHT"
.br
