'\" t
.\"     Title: insert_resource_expand_to_fit
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: January 2017
.\"    Manual: Hardware Interfaces
.\"    Source: Kernel Hackers Manual 4.10.0-rc1
.\"  Language: English
.\"
.TH "INSERT_RESOURCE_EXPA" "9" "January 2017" "Kernel Hackers Manual 4\&.10\&" "Hardware Interfaces"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
insert_resource_expand_to_fit \- Insert a resource into the resource tree
.SH "SYNOPSIS"
.HP \w'void\ insert_resource_expand_to_fit('u
.BI "void insert_resource_expand_to_fit(struct\ resource\ *\ " "root" ", struct\ resource\ *\ " "new" ");"
.SH "ARGUMENTS"
.PP
\fIroot\fR
.RS 4
root resource descriptor
.RE
.PP
\fInew\fR
.RS 4
new resource to insert
.RE
.SH "DESCRIPTION"
.PP
Insert a resource into the resource tree, possibly expanding it in order to make it encompass any conflicting resources\&.
.SH "COPYRIGHT"
.br
