'\" t
.\"     Title: ipc_check_perms
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: January 2017
.\"    Manual: Kernel IPC facilities
.\"    Source: Kernel Hackers Manual 4.10.0-rc1
.\"  Language: English
.\"
.TH "IPC_CHECK_PERMS" "9" "January 2017" "Kernel Hackers Manual 4\&.10\&" "Kernel IPC facilities"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
ipc_check_perms \- check security and permissions for an ipc object
.SH "SYNOPSIS"
.HP \w'int\ ipc_check_perms('u
.BI "int ipc_check_perms(struct\ ipc_namespace\ *\ " "ns" ", struct\ kern_ipc_perm\ *\ " "ipcp" ", const\ struct\ ipc_ops\ *\ " "ops" ", struct\ ipc_params\ *\ " "params" ");"
.SH "ARGUMENTS"
.PP
\fIns\fR
.RS 4
ipc namespace
.RE
.PP
\fIipcp\fR
.RS 4
ipc permission set
.RE
.PP
\fIops\fR
.RS 4
the actual security routine to call
.RE
.PP
\fIparams\fR
.RS 4
its parameters
.RE
.SH "DESCRIPTION"
.PP
This routine is called by
\fBsys_msgget\fR,
\fBsys_semget\fR
and
\fBsys_shmget\fR
when the key is not IPC_PRIVATE and that key already exists in the ds IDR\&.
.PP
On success, the ipc id is returned\&.
.PP
It is called with ipc_ids\&.rwsem and ipcp\->lock held\&.
.SH "COPYRIGHT"
.br
