'\" t
.\"     Title: kgdb_arch_late
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: January 2017
.\"    Manual: Kernel Debugger Internals
.\"    Source: Kernel Hackers Manual 4.10.0-rc1
.\"  Language: English
.\"
.TH "KGDB_ARCH_LATE" "9" "January 2017" "Kernel Hackers Manual 4\&.10\&" "Kernel Debugger Internals"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
kgdb_arch_late \- Perform any architecture specific initalization\&.
.SH "SYNOPSIS"
.HP \w'void\ kgdb_arch_late('u
.BI "void kgdb_arch_late(" "void" ");"
.SH "ARGUMENTS"
.PP
\fIvoid\fR
.RS 4
no arguments
.RE
.SH "DESCRIPTION"
.PP
.PP
This function will handle the late initalization of any architecture specific callbacks\&. This is an optional function for handling things like late initialization of hw breakpoints\&. The default implementation does nothing\&.
.SH "AUTHOR"
.PP
\fBJason Wessel\fR <\&jason.wessel@windriver.com\&>
.RS 4
Author.
.RE
.SH "COPYRIGHT"
.br
