'\" t
.\"     Title: memdup_user
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: January 2017
.\"    Manual: Memory Management in Linux
.\"    Source: Kernel Hackers Manual 4.10.0-rc1
.\"  Language: English
.\"
.TH "MEMDUP_USER" "9" "January 2017" "Kernel Hackers Manual 4\&.10\&" "Memory Management in Linux"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
memdup_user \- duplicate memory region from user space
.SH "SYNOPSIS"
.HP \w'void\ *\ memdup_user('u
.BI "void * memdup_user(const\ void\ __user\ *\ " "src" ", size_t\ " "len" ");"
.SH "ARGUMENTS"
.PP
\fIsrc\fR
.RS 4
source address in user space
.RE
.PP
\fIlen\fR
.RS 4
number of bytes to copy
.RE
.SH "DESCRIPTION"
.PP
Returns an
\fBERR_PTR\fR
on failure\&.
.SH "COPYRIGHT"
.br
