'\" t
.\"     Title: nand_setup_data_interface
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: January 2017
.\"    Manual: Internal Functions Provided
.\"    Source: Kernel Hackers Manual 4.10.0-rc1
.\"  Language: English
.\"
.TH "NAND_SETUP_DATA_INTE" "9" "January 2017" "Kernel Hackers Manual 4\&.10\&" "Internal Functions Provided"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
nand_setup_data_interface \- Setup the best data interface and timings
.SH "SYNOPSIS"
.HP \w'int\ nand_setup_data_interface('u
.BI "int nand_setup_data_interface(struct\ nand_chip\ *\ " "chip" ");"
.SH "ARGUMENTS"
.PP
\fIchip\fR
.RS 4
The NAND chip
.RE
.SH "DESCRIPTION"
.PP
Find and configure the best data interface and NAND timings supported by the chip and the driver\&. First tries to retrieve supported timing modes from ONFI information, and if the NAND chip does not support ONFI, relies on the \->onfi_timing_mode_default specified in the nand_ids table\&.
.PP
Returns 0 for success or negative error code otherwise\&.
.SH "AUTHOR"
.PP
\fBThomas Gleixner\fR <\&tglx@linutronix.de\&>
.RS 4
Author.
.RE
.SH "COPYRIGHT"
.br
