'\" t
.\"     Title: proc_dointvec_jiffies
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: January 2017
.\"    Manual: The proc filesystem
.\"    Source: Kernel Hackers Manual 4.10.0-rc1
.\"  Language: English
.\"
.TH "PROC_DOINTVEC_JIFFIE" "9" "January 2017" "Kernel Hackers Manual 4\&.10\&" "The proc filesystem"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
proc_dointvec_jiffies \- read a vector of integers as seconds
.SH "SYNOPSIS"
.HP \w'int\ proc_dointvec_jiffies('u
.BI "int proc_dointvec_jiffies(struct\ ctl_table\ *\ " "table" ", int\ " "write" ", void\ __user\ *\ " "buffer" ", size_t\ *\ " "lenp" ", loff_t\ *\ " "ppos" ");"
.SH "ARGUMENTS"
.PP
\fItable\fR
.RS 4
the sysctl table
.RE
.PP
\fIwrite\fR
.RS 4
\fBTRUE\fR
if this is a write to the sysctl file
.RE
.PP
\fIbuffer\fR
.RS 4
the user buffer
.RE
.PP
\fIlenp\fR
.RS 4
the size of the user buffer
.RE
.PP
\fIppos\fR
.RS 4
file position
.RE
.SH "DESCRIPTION"
.PP
Reads/writes up to table\->maxlen/sizeof(unsigned int) integer values from/to the user buffer, treated as an ASCII string\&. The values read are assumed to be in seconds, and are converted into jiffies\&.
.PP
Returns 0 on success\&.
.SH "COPYRIGHT"
.br
