'\" t
.\"     Title: regulator_bulk_register_supply_alias
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: January 2017
.\"    Manual: API reference
.\"    Source: Kernel Hackers Manual 4.10.0-rc1
.\"  Language: English
.\"
.TH "REGULATOR_BULK_REGIS" "9" "January 2017" "Kernel Hackers Manual 4\&.10\&" "API reference"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
regulator_bulk_register_supply_alias \- register multiple aliases
.SH "SYNOPSIS"
.HP \w'int\ regulator_bulk_register_supply_alias('u
.BI "int regulator_bulk_register_supply_alias(struct\ device\ *\ " "dev" ", const\ char\ *const\ *\ " "id" ", struct\ device\ *\ " "alias_dev" ", const\ char\ *const\ *\ " "alias_id" ", int\ " "num_id" ");"
.SH "ARGUMENTS"
.PP
\fIdev\fR
.RS 4
device that will be given as the regulator
\(lqconsumer\(rq
.RE
.PP
\fIid\fR
.RS 4
List of supply names or regulator IDs
.RE
.PP
\fIalias_dev\fR
.RS 4
device that should be used to lookup the supply
.RE
.PP
\fIalias_id\fR
.RS 4
List of supply names or regulator IDs that should be used to lookup the supply
.RE
.PP
\fInum_id\fR
.RS 4
Number of aliases to register
.RE
.SH "DESCRIPTION"
.PP
\fIreturn\fR
0 on success, an errno on failure\&.
.PP
This helper function allows drivers to register several supply aliases in one operation\&. If any of the aliases cannot be registered any aliases that were registered will be removed before returning to the caller\&.
.SH "AUTHORS"
.PP
\fBLiam Girdwood\fR <\&lrg@slimlogic.co.uk\&>
.RS 4
Author.
.RE
.PP
\fBMark Brown\fR <\&broonie@opensource.wolfsonmicro.com\&>
.br
Wolfson Microelectronics, 
      
     
.RS 4
Author.
.RE
.SH "COPYRIGHT"
.br
