'\" t
.\"     Title: regulator_set_mode
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: January 2017
.\"    Manual: API reference
.\"    Source: Kernel Hackers Manual 4.10.0-rc1
.\"  Language: English
.\"
.TH "REGULATOR_SET_MODE" "9" "January 2017" "Kernel Hackers Manual 4\&.10\&" "API reference"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
regulator_set_mode \- set regulator operating mode
.SH "SYNOPSIS"
.HP \w'int\ regulator_set_mode('u
.BI "int regulator_set_mode(struct\ regulator\ *\ " "regulator" ", unsigned\ int\ " "mode" ");"
.SH "ARGUMENTS"
.PP
\fIregulator\fR
.RS 4
regulator source
.RE
.PP
\fImode\fR
.RS 4
operating mode \- one of the REGULATOR_MODE constants
.RE
.SH "DESCRIPTION"
.PP
Set regulator operating mode to increase regulator efficiency or improve regulation performance\&.
.SH "NOTE"
.PP
Regulator system constraints must be set for this regulator before calling this function otherwise this call will fail\&.
.SH "AUTHORS"
.PP
\fBLiam Girdwood\fR <\&lrg@slimlogic.co.uk\&>
.RS 4
Author.
.RE
.PP
\fBMark Brown\fR <\&broonie@opensource.wolfsonmicro.com\&>
.br
Wolfson Microelectronics, 
      
     
.RS 4
Author.
.RE
.SH "COPYRIGHT"
.br
