'\" t
.\"     Title: remap_vmalloc_range
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: January 2017
.\"    Manual: Memory Management in Linux
.\"    Source: Kernel Hackers Manual 4.10.0-rc1
.\"  Language: English
.\"
.TH "REMAP_VMALLOC_RANGE" "9" "January 2017" "Kernel Hackers Manual 4\&.10\&" "Memory Management in Linux"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
remap_vmalloc_range \- map vmalloc pages to userspace
.SH "SYNOPSIS"
.HP \w'int\ remap_vmalloc_range('u
.BI "int remap_vmalloc_range(struct\ vm_area_struct\ *\ " "vma" ", void\ *\ " "addr" ", unsigned\ long\ " "pgoff" ");"
.SH "ARGUMENTS"
.PP
\fIvma\fR
.RS 4
vma to cover (map full range of vma)
.RE
.PP
\fIaddr\fR
.RS 4
vmalloc memory
.RE
.PP
\fIpgoff\fR
.RS 4
number of pages into addr before first page to map
.RE
.SH "RETURN"
.PP
0 for success, \-Exxx on failure
.PP
This function checks that addr is a valid vmalloc\*(Aqed area, and that it is big enough to cover the vma\&. Will return failure if that criteria isn\*(Aqt met\&.
.PP
Similar to
\fBremap_pfn_range\fR
(see mm/memory\&.c)
.SH "COPYRIGHT"
.br
