'\" t
.\"     Title: rio_disc_mport
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: January 2017
.\"    Manual: Internals
.\"    Source: Kernel Hackers Manual 4.10.0-rc1
.\"  Language: English
.\"
.TH "RIO_DISC_MPORT" "9" "January 2017" "Kernel Hackers Manual 4\&.10\&" "Internals"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
rio_disc_mport \- Start discovery through a master port
.SH "SYNOPSIS"
.HP \w'int\ rio_disc_mport('u
.BI "int rio_disc_mport(struct\ rio_mport\ *\ " "mport" ", u32\ " "flags" ");"
.SH "ARGUMENTS"
.PP
\fImport\fR
.RS 4
Master port to send transactions
.RE
.PP
\fIflags\fR
.RS 4
discovery control flags
.RE
.SH "DESCRIPTION"
.PP
Starts the discovery process\&. If we have an active link, then wait for the signal that enumeration is complete (if wait is allowed)\&. When enumeration completion is signaled, start recursive peer discovery\&. Returns
\fB0\fR
if discovery succeeds or
\fB\-EBUSY\fR
on failure\&.
.SH "AUTHOR"
.PP
\fBMatt Porter\fR <\&mporter@kernel.crashing.org\&>, <\&mporter@mvista.com\&>
.RS 4
Author.
.RE
.SH "COPYRIGHT"
.br
