'\" t
.\"     Title: scsi_report_lun_scan
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: January 2017
.\"    Manual: SCSI mid layer
.\"    Source: Kernel Hackers Manual 4.10.0-rc1
.\"  Language: English
.\"
.TH "SCSI_REPORT_LUN_SCAN" "9" "January 2017" "Kernel Hackers Manual 4\&.10\&" "SCSI mid layer"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
scsi_report_lun_scan \- Scan using SCSI REPORT LUN results
.SH "SYNOPSIS"
.HP \w'int\ scsi_report_lun_scan('u
.BI "int scsi_report_lun_scan(struct\ scsi_target\ *\ " "starget" ", int\ " "bflags" ", enum\ scsi_scan_mode\ " "rescan" ");"
.SH "ARGUMENTS"
.PP
\fIstarget\fR
.RS 4
which target
.RE
.PP
\fIbflags\fR
.RS 4
Zero or a mix of BLIST_NOLUN, BLIST_REPORTLUN2, or BLIST_NOREPORTLUN
.RE
.PP
\fIrescan\fR
.RS 4
nonzero if we can skip code only needed on first scan
.RE
.SH "DESCRIPTION"
.PP
Fast scanning for modern (SCSI\-3) devices by sending a REPORT LUN command\&. Scan the resulting list of LUNs by calling scsi_probe_and_add_lun\&.
.PP
If BLINK_REPORTLUN2 is set, scan a target that supports more than 8 LUNs even if it\*(Aqs older than SCSI\-3\&. If BLIST_NOREPORTLUN is set, return 1 always\&. If BLIST_NOLUN is set, return 0 always\&. If starget\->no_report_luns is set, return 1 always\&.
.SH "RETURN"
.PP
0: scan completed (or no memory, so further scanning is futile) 1: could not scan with REPORT LUN
.SH "AUTHORS"
.PP
\fBJames Bottomley\fR <\&James.Bottomley@hansenpartnership.com\&>
.RS 4
Author.
.RE
.PP
\fBRob Landley\fR <\&rob@landley.net\&>
.RS 4
Author.
.RE
.SH "COPYRIGHT"
.br
