'\" t
.\"     Title: scsi_target_reap
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: January 2017
.\"    Manual: SCSI mid layer
.\"    Source: Kernel Hackers Manual 4.10.0-rc1
.\"  Language: English
.\"
.TH "SCSI_TARGET_REAP" "9" "January 2017" "Kernel Hackers Manual 4\&.10\&" "SCSI mid layer"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
scsi_target_reap \- check to see if target is in use and destroy if not
.SH "SYNOPSIS"
.HP \w'void\ scsi_target_reap('u
.BI "void scsi_target_reap(struct\ scsi_target\ *\ " "starget" ");"
.SH "ARGUMENTS"
.PP
\fIstarget\fR
.RS 4
target to be checked
.RE
.SH "DESCRIPTION"
.PP
This is used after removing a LUN or doing a last put of the target it checks atomically that nothing is using the target and removes it if so\&.
.SH "AUTHORS"
.PP
\fBJames Bottomley\fR <\&James.Bottomley@hansenpartnership.com\&>
.RS 4
Author.
.RE
.PP
\fBRob Landley\fR <\&rob@landley.net\&>
.RS 4
Author.
.RE
.SH "COPYRIGHT"
.br
