'\" t
.\"     Title: seq_lseek
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: January 2017
.\"    Manual: The Linux VFS
.\"    Source: Kernel Hackers Manual 4.10.0-rc1
.\"  Language: English
.\"
.TH "SEQ_LSEEK" "9" "January 2017" "Kernel Hackers Manual 4\&.10\&" "The Linux VFS"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
seq_lseek \- \->\fBllseek\fR method for sequential files\&.
.SH "SYNOPSIS"
.HP \w'loff_t\ seq_lseek('u
.BI "loff_t seq_lseek(struct\ file\ *\ " "file" ", loff_t\ " "offset" ", int\ " "whence" ");"
.SH "ARGUMENTS"
.PP
\fIfile\fR
.RS 4
the file in question
.RE
.PP
\fIoffset\fR
.RS 4
new position
.RE
.PP
\fIwhence\fR
.RS 4
0 for absolute, 1 for relative position
.RE
.SH "DESCRIPTION"
.PP
Ready\-made \->f_op\->\fBllseek\fR
.SH "COPYRIGHT"
.br
