'\" t
.\"     Title: skb_cloned
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: January 2017
.\"    Manual: Linux Networking
.\"    Source: Kernel Hackers Manual 4.10.0-rc1
.\"  Language: English
.\"
.TH "SKB_CLONED" "9" "January 2017" "Kernel Hackers Manual 4\&.10\&" "Linux Networking"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
skb_cloned \- is the buffer a clone
.SH "SYNOPSIS"
.HP \w'int\ skb_cloned('u
.BI "int skb_cloned(const\ struct\ sk_buff\ *\ " "skb" ");"
.SH "ARGUMENTS"
.PP
\fIskb\fR
.RS 4
buffer to check
.RE
.SH "DESCRIPTION"
.PP
Returns true if the buffer was generated with
\fBskb_clone\fR
and is one of multiple shared copies of the buffer\&. Cloned buffers are shared data so must not be written to under normal circumstances\&.
.SH "COPYRIGHT"
.br
