'\" t
.\"     Title: struct clk_notifier_data
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: January 2017
.\"    Manual: Clock Framework
.\"    Source: Kernel Hackers Manual 4.10.0-rc1
.\"  Language: English
.\"
.TH "STRUCT CLK_NOTIFIER_" "9" "January 2017" "Kernel Hackers Manual 4\&.10\&" "Clock Framework"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
struct_clk_notifier_data \- rate data to pass to the notifier callback
.SH "SYNOPSIS"
.sp
.nf
struct clk_notifier_data {
  struct clk * clk;
  unsigned long old_rate;
  unsigned long new_rate;
};  
.fi
.SH "MEMBERS"
.PP
clk
.RS 4
struct clk * being changed
.RE
.PP
old_rate
.RS 4
previous rate of this clk
.RE
.PP
new_rate
.RS 4
new rate of this clk
.RE
.SH "DESCRIPTION"
.PP
For a pre\-notifier, old_rate is the clk\*(Aqs rate before this rate change, and new_rate is what the rate will be in the future\&. For a post\-notifier, old_rate and new_rate are both set to the clk\*(Aqs current rate (this was done to optimize the implementation)\&.
.SH "COPYRIGHT"
.br
