'\" t
.\"     Title: struct iio_chan_spec
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: January 2017
.\"    Manual: Industrial I/O core
.\"    Source: Kernel Hackers Manual 4.10.0-rc1
.\"  Language: English
.\"
.TH "STRUCT IIO_CHAN_SPEC" "9" "January 2017" "Kernel Hackers Manual 4\&.10\&" "Industrial I/O core"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
struct_iio_chan_spec \- specification of a single channel
.SH "SYNOPSIS"
.sp
.nf
struct iio_chan_spec {
  enum iio_chan_type type;
  int channel;
  int channel2;
  unsigned long address;
  int scan_index;
  struct scan_type;
  long info_mask_separate;
  long info_mask_separate_available;
  long info_mask_shared_by_type;
  long info_mask_shared_by_type_available;
  long info_mask_shared_by_dir;
  long info_mask_shared_by_dir_available;
  long info_mask_shared_by_all;
  long info_mask_shared_by_all_available;
  const struct iio_event_spec * event_spec;
  unsigned int num_event_specs;
  const struct iio_chan_spec_ext_info * ext_info;
  const char * extend_name;
  const char * datasheet_name;
  unsigned modified:1;
  unsigned indexed:1;
  unsigned output:1;
  unsigned differential:1;
};  
.fi
.SH "MEMBERS"
.PP
type
.RS 4
What type of measurement is the channel making\&.
.RE
.PP
channel
.RS 4
What number do we wish to assign the channel\&.
.RE
.PP
channel2
.RS 4
If there is a second number for a differential channel then this is it\&. If modified is set then the value here specifies the modifier\&.
.RE
.PP
address
.RS 4
Driver specific identifier\&.
.RE
.PP
scan_index
.RS 4
Monotonic index to give ordering in scans when read from a buffer\&.
.RE
.PP
scan_type
.RS 4
sign: \*(Aqs\*(Aq or \*(Aqu\*(Aq to specify signed or unsigned realbits: Number of valid bits of data storagebits: Realbits + padding shift: Shift right by this before masking out realbits\&. repeat: Number of times real/storage bits repeats\&. When the repeat element is more than 1, then the type element in sysfs will show a repeat value\&. Otherwise, the number of repetitions is omitted\&. endianness: little or big endian
.RE
.PP
info_mask_separate
.RS 4
What information is to be exported that is specific to this channel\&.
.RE
.PP
info_mask_separate_available
.RS 4
What availability information is to be exported that is specific to this channel\&.
.RE
.PP
info_mask_shared_by_type
.RS 4
What information is to be exported that is shared by all channels of the same type\&.
.RE
.PP
info_mask_shared_by_type_available
.RS 4
What availability information is to be exported that is shared by all channels of the same type\&.
.RE
.PP
info_mask_shared_by_dir
.RS 4
What information is to be exported that is shared by all channels of the same direction\&.
.RE
.PP
info_mask_shared_by_dir_available
.RS 4
What availability information is to be exported that is shared by all channels of the same direction\&.
.RE
.PP
info_mask_shared_by_all
.RS 4
What information is to be exported that is shared by all channels\&.
.RE
.PP
info_mask_shared_by_all_available
.RS 4
What availability information is to be exported that is shared by all channels\&.
.RE
.PP
event_spec
.RS 4
Array of events which should be registered for this channel\&.
.RE
.PP
num_event_specs
.RS 4
Size of the event_spec array\&.
.RE
.PP
ext_info
.RS 4
Array of extended info attributes for this channel\&. The array is NULL terminated, the last element should have its name field set to NULL\&.
.RE
.PP
extend_name
.RS 4
Allows labeling of channel attributes with an informative name\&. Note this has no effect codes etc, unlike modifiers\&.
.RE
.PP
datasheet_name
.RS 4
A name used in in\-kernel mapping of channels\&. It should correspond to the first name that the channel is referred to by in the datasheet (e\&.g\&. IND), or the nearest possible compound name (e\&.g\&. IND\-INC)\&.
.RE
.PP
modified
.RS 4
Does a modifier apply to this channel\&. What these are depends on the channel type\&. Modifier is set in channel2\&. Examples are IIO_MOD_X for axial sensors about the \*(Aqx\*(Aq axis\&.
.RE
.PP
indexed
.RS 4
Specify the channel has a numerical index\&. If not, the channel index number will be suppressed for sysfs attributes but not for event codes\&.
.RE
.PP
output
.RS 4
Channel is output\&.
.RE
.PP
differential
.RS 4
Channel is differential\&.
.RE
.SH "AUTHOR"
.PP
\fBDaniel Baluta\fR <\&daniel.baluta@intel.com\&>
.RS 4
Author.
.RE
.SH "COPYRIGHT"
.br
