'\" t
.\"     Title: vscnprintf
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: January 2017
.\"    Manual: Basic C Library Functions
.\"    Source: Kernel Hackers Manual 4.10.0-rc1
.\"  Language: English
.\"
.TH "VSCNPRINTF" "9" "January 2017" "Kernel Hackers Manual 4\&.10\&" "Basic C Library Functions"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
vscnprintf \- Format a string and place it in a buffer
.SH "SYNOPSIS"
.HP \w'int\ vscnprintf('u
.BI "int vscnprintf(char\ *\ " "buf" ", size_t\ " "size" ", const\ char\ *\ " "fmt" ", va_list\ " "args" ");"
.SH "ARGUMENTS"
.PP
\fIbuf\fR
.RS 4
The buffer to place the result into
.RE
.PP
\fIsize\fR
.RS 4
The size of the buffer, including the trailing null space
.RE
.PP
\fIfmt\fR
.RS 4
The format string to use
.RE
.PP
\fIargs\fR
.RS 4
Arguments for the format string
.RE
.SH "DESCRIPTION"
.PP
The return value is the number of characters which have been written into the
\fIbuf\fR
not including the trailing \*(Aq\e0\*(Aq\&. If
\fIsize\fR
is == 0 the function returns 0\&.
.PP
If you\*(Aqre not already dealing with a va_list consider using
\fBscnprintf\fR\&.
.PP
See the
\fBvsnprintf\fR
documentation for format string extensions over C99\&.
.SH "COPYRIGHT"
.br
