'\" t
.\"     Title: xdr_init_decode_pages
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: January 2017
.\"    Manual: Linux Networking
.\"    Source: Kernel Hackers Manual 4.10.0-rc1
.\"  Language: English
.\"
.TH "XDR_INIT_DECODE_PAGE" "9" "January 2017" "Kernel Hackers Manual 4\&.10\&" "Linux Networking"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
xdr_init_decode_pages \- Initialize an xdr_stream for decoding data\&.
.SH "SYNOPSIS"
.HP \w'void\ xdr_init_decode_pages('u
.BI "void xdr_init_decode_pages(struct\ xdr_stream\ *\ " "xdr" ", struct\ xdr_buf\ *\ " "buf" ", struct\ page\ **\ " "pages" ", unsigned\ int\ " "len" ");"
.SH "ARGUMENTS"
.PP
\fIxdr\fR
.RS 4
pointer to xdr_stream struct
.RE
.PP
\fIbuf\fR
.RS 4
pointer to XDR buffer from which to decode data
.RE
.PP
\fIpages\fR
.RS 4
list of pages to decode into
.RE
.PP
\fIlen\fR
.RS 4
length in bytes of buffer in pages
.RE
.SH "COPYRIGHT"
.br
