'\" t
.\"     Title: xdr_inline_decode
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: January 2017
.\"    Manual: Linux Networking
.\"    Source: Kernel Hackers Manual 4.10.0-rc1
.\"  Language: English
.\"
.TH "XDR_INLINE_DECODE" "9" "January 2017" "Kernel Hackers Manual 4\&.10\&" "Linux Networking"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
xdr_inline_decode \- Retrieve XDR data to decode
.SH "SYNOPSIS"
.HP \w'__be32\ *\ xdr_inline_decode('u
.BI "__be32 * xdr_inline_decode(struct\ xdr_stream\ *\ " "xdr" ", size_t\ " "nbytes" ");"
.SH "ARGUMENTS"
.PP
\fIxdr\fR
.RS 4
pointer to xdr_stream struct
.RE
.PP
\fInbytes\fR
.RS 4
number of bytes of data to decode
.RE
.SH "DESCRIPTION"
.PP
Check if the input buffer is long enough to enable us to decode \*(Aqnbytes\*(Aq more bytes of data starting at the current position\&. If so return the current pointer, then update the current pointer position\&.
.SH "COPYRIGHT"
.br
