'\" t
.\"     Title: xprt_lookup_rqst
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: January 2017
.\"    Manual: Linux Networking
.\"    Source: Kernel Hackers Manual 4.10.0-rc1
.\"  Language: English
.\"
.TH "XPRT_LOOKUP_RQST" "9" "January 2017" "Kernel Hackers Manual 4\&.10\&" "Linux Networking"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
xprt_lookup_rqst \- find an RPC request corresponding to an XID
.SH "SYNOPSIS"
.HP \w'struct\ rpc_rqst\ *\ xprt_lookup_rqst('u
.BI "struct rpc_rqst * xprt_lookup_rqst(struct\ rpc_xprt\ *\ " "xprt" ", __be32\ " "xid" ");"
.SH "ARGUMENTS"
.PP
\fIxprt\fR
.RS 4
transport on which the original request was transmitted
.RE
.PP
\fIxid\fR
.RS 4
RPC XID of incoming reply
.RE
.SH "COPYRIGHT"
.br
