#!/bin/sh

for f; do
	case "$f" in
	*.h)
		set -- --language=C "$@"
		break ;;
	*.hpp)
		set -- --language=C++ "$@"
		break ;;
	*.txt)
		set -- --language=Markdown "$@"
		break ;;
	esac
done

# stdin
if test -z "$*"; then
	set -- --language=C
fi

# set -- --theme=1337 "$@"
set -- --theme=DarkNeon "$@"

exec bat "$@"
