#!/bin/sh

kern_dir=/store/code/projects/kernel/linux
cwd="$PWD"

cd "$kern_dir" || exit 1

trap '{ cd "$cwd"; trap - INT; kill -INT $$; }' INT
trap '{ cd "$cwd"; exit; }' EXIT

cscope -f cscope.out -Rvqk "$@"

kill -INT "$$"
