#!/bin/perl

my $i=0;my @text;my %h;map {my $_j_=0;map{$h{lc $_}=lc $_ cmp $_;}split "",$_; $text[$i]=lc $_;$text[$i]=~s/l+\b/rru/g;$text[$i]=~s/l\B/r/g;$text[$i]=~s/(?<![\baeiouy])([sfrpgt]+)\b/$1u/g;$text[$i]=~s/(?<=[\baeiouy])([dpfzmtnrg]+)\b/$1o/g;$text[$i]=~s/c+([ee])/kush$1/g;$text[$i++]=~s/c+([aeiou])/k$1/g;}@ARGV;for (1 .. scalar @text){my $_j_=$_-1; map{$text[$_j_] =~ s/(.*)/\U$&/ if $h{$_}} split "",$text[$_j_]} print "/say ".join " ",@text;

#my $i=0;my @text;my %h;map {my $_j_=0,$word=$_;map{$h{$word}=(lc $_ cmp $_) << $i;}split "",$_; $text[$i]=lc $_;$text[$i]=~s/l+\b/rru/g;$text[$i]=~s/l\B/r/g;$text[$i]=~s/(?<![\baeiouy])([sfrpgt]+)\b/$1u/g;$text[$i]=~s/(?<=[\baeiouy])([dpfzmtnrg]+)\b/$1o/g;$text[$i]=~s/c+([ee])/kush$1/g;$text[$i++]=~s/c+([aeiou])/k$1/g;}@ARGV;for (1 .. scalar @text){$i=0,my $_j_=$_-1, $_k_=0;map{$word=$text[$i];$text[$_j_] =~ s/(@{[split "",$text[$_j_]]}[$_k_])/\U$&/ if print $h{$word}; $_k_++; $i++;} split "",$text[$_j_]} print "/say ".join " ",@text;
