#!/bin/sh

unset LIBGL_DRI3_DISABLE
# export LIBGL_DRI3_DISABLE=1
export DRI_PRIME=1
export LIBVA_DRIVER_NAME=vdpau
export VDPAU_DRIVER=nvidia

primusrun /usr/bin/mpv "$@" || /usr/bin/mpv --vo=xv "$@"
