#!/bin/sh

export PERL5LIB=/usr/lib/pisg/modules

cwd="$PWD"
trap '{ cd $cwd; trap - INT; kill -INT $$; }' INT
trap '{ cd $cwd; }' EXIT ERR
cd /usr/share/pisg || exit 1

pisg -co /etc/aot.cfg "$@"
pisg -co /etc/chee.cfg "$@"
pisg -co /etc/void.cfg "$@"
# exec pisg "$@"
