#!/bin/perl

use strict;
use warnings;

my $user = "alyptik";
my $url = "https://www.pornhub.com/users/$user/videos/favorites";
my ($flag, $cnt, $results) = (0, 0, ($ARGV[$#ARGV] // 1));
my (@hash_list, @url_list);

foreach (split "\n", `curl -s '$url'`) {
	next unless (/Play All Videos/ .. eof);
	if (/view_video\.php\?viewkey=([^"]+)" title="([^"]+)"/ && ++$flag % 2) {
		my ($name, $url, $vid) = ("", "", "");
		$name = $2;
		$url = "https://pornhub.com/view_video.php?viewkey=$1";
		chomp($vid = `youtube-dl --get-url "$url"`) if $#ARGV;
		push @hash_list, {
			name => $name,
			vid => $vid,
			url => $url,
		};
		push @url_list, $url;
		last unless ++$cnt < $results;
	}
}

foreach (0 .. $results - 1) {
	if (!$#ARGV) {
		print "[$hash_list[$_]->{name}] <$hash_list[$_]->{url}>\n";
	} else {
		system("saldl -ro '/store/stuff/$hash_list[$_]->{name}.mp4' '$hash_list[$_]->{vid}'");
	}
}

print "\n";
print STDERR join " ", @url_list;
print "\n\n";

# vi:ft=perl:
