#!/bin/zsh

# domains=(alyp.tk sigfu.tk fsckingfu.tk)
# subs=(mail cube www webmail stream)
# list=($(print ${(j:,:)domains},$(printf '%s.%s,' {${^subs},${^domains}})))
#
# sudo systemctl stop nginx
#
# sudo certbot renew
# sudo certbot certonly --standalone -d "${list%%,}"
# sudo certbot certonly --standalone -d "${list%%,},hewillnotdivide.tk"

# sudo systemctl start nginx

domains=(-d alyp.tk -d sigfu.tk -d fsckingfu.tk)
wildcards=(-d '*.alyp.tk' -d '*.sigfu.tk' -d '*.fsckingfu.tk')
sudo certbot certonly --manual $domains $wildcards --server https://acme-v02.api.letsencrypt.org/directory
