#!/bin/env python2
# EASY-INSTALL-ENTRY-SCRIPT: 'rrapper==0.1.0','console_scripts','rrtest'

__requires__ = 'rrapper==0.1.0'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('rrapper==0.1.0', 'console_scripts', 'rrtest')()
    )
