#!/bin/bash

# setup variables
usage_string="usage: /bin/your_cmd | ${0##*/} \"[./build.log]\""
append_flag=0
out_files=()
log_file=""
tmp_file="$(mktemp)"

if [[ -t 0 ]]; then
	printf '%s\n' "$usage_string" >&2
	exit 1
fi

exec 3<>"$tmp_file"
trap '{ rm -fv "$tmp_file"; exec 3>&-; }' ERR EXIT
trap '{ rm -fv "$tmp_file"; exec 3>&-; trap - INT; kill -INT "$$"; }' INT

while getopts :aho: opt; do
	case "$opt" in
	a)
		append_flag=1
		;;
	o)
		out_files+=("$OPTARG")
		;;
	h)
		printf '%s\n' "$usage_string" >&2
		exit
		;;
	:|?)
		printf 'illegal option: -%s\n' "$OPTARG" >&2
		printf '%s\n' "$usage_string" >&2
		exit 1
		;;
	esac
done
shift "$((OPTIND - 1))"


log_file="${*:-./build.log}"

if ((!append_flag)); then
	:>"$log_file"
fi

perl -e 'print "\n", "—"x72, "\nCompilation started at: ". `date`, "—"x72, "\n\n"' \
	| tee -a "$log_file"
tee -a "$log_file" </dev/stdin
cat <"$log_file" >&3

for file in "${out_files[@]}"; do
	(cat </dev/stdin >"$file") <&3
done
