#!/bin/sh
# Uses a unicode-aware sed to translate ascii chars to full-width equivalent

# functions for (sed|printf)-quoting a string (
A () { printf "$A" | sed -e 's,\([][\/]\),\\\1,g' -e 's,%,%%,g' ; }
U () { printf "$U" | sed -e 's,\([][\/]\),\\\1,g' -e 's,%,%%,g' ; }
Y () { printf "$Y"; }

A=$"$(printf '%s%s%s%s%s%s%s%s%s%s%s%s\n' \
    '\x20\x21\x22\x23\x24\x25\x26\x27' \
    '\x28\x29\x2A\x2B\x2C\x2D\x2E\x2F' \
    '\x30\x31\x32\x33\x34\x35\x36\x37' \
    '\x38\x39\x3A\x3B\x3C\x3D\x3E\x3F' \
    '\x40\x41\x42\x43\x44\x45\x46\x47' \
    '\x48\x49\x4A\x4B\x4C\x4D\x4E\x4F' \
    '\x50\x51\x52\x53\x54\x55\x56\x57' \
    '\x58\x59\x5A\x5B\x5C\x5D\x5E\x5F' \
    '\x60\x61\x62\x63\x64\x65\x66\x67' \
    '\x68\x69\x6A\x6B\x6C\x6D\x6E\x6F' \
    '\x70\x71\x72\x73\x74\x75\x76\x77' \
    '\x78\x79\x7A\x7B\x7C\x7D\x7E'   )"

U="$(printf '%s%s%s%s%s%s%s%s%s%s%s%s\n' \
    '\u3000\uFF01\uFF02\uFF03\uFF04\uFF05\uFF06\uFF07' \
    '\uFF08\uFF09\uFF0A\uFF0B\uFF0C\uFF0D\uFF0E\uFF0F' \
    '\uFF10\uFF11\uFF12\uFF13\uFF14\uFF15\uFF16\uFF17' \
    '\uFF18\uFF19\uFF1A\uFF1B\uFF1C\uFF1D\uFF1E\uFF1F' \
    '\uFF20\uFF21\uFF22\uFF23\uFF24\uFF25\uFF26\uFF27' \
    '\uFF28\uFF29\uFF2A\uFF2B\uFF2C\uFF2D\uFF2E\uFF2F' \
    '\uFF30\uFF31\uFF32\uFF33\uFF34\uFF35\uFF36\uFF37' \
    '\uFF38\uFF39\uFF3A\uFF3B\uFF3C\uFF3D\uFF3E\uFF3F' \
    '\uFF40\uFF41\uFF42\uFF43\uFF44\uFF45\uFF46\uFF47' \
    '\uFF48\uFF49\uFF4A\uFF4B\uFF4C\uFF4D\uFF4E\uFF4F' \
    '\uFF50\uFF51\uFF52\uFF53\uFF54\uFF55\uFF56\uFF57' \
    '\uFF58\uFF59\uFF5A\uFF5B\uFF5C\uFF5D\uFF5E'       )"

Y="$(printf 'y/%s/%s/' "$(A)" "$(U)")"

section () {
  printf '_________________________\n'
  cat
  printf '^^^^^^^^^^^^^^^^^^^^^^^^^\n\n'
}

[[ $DEBUG ]] && {
  set -v
  locale 
  #export LANG="en_US.UTF-8"
  #export LC_ALL="en_US.UTF-8"
  echo "$A" | section
  echo "$U" | section
  echo "$Y" | section
  A | section
  U | section
  Y | section
}

exec sed -e "$(Y)" "$@"

