#!/bin/sh

eurl() {
	local LC_ALL=C c
	while IFS= read -r -n1 -d '' c
	do
	if [[ "$c" == [[:alnum:]] ]]; then
		printf %s "$c"
	else
		printf %%%02x "'$c"
	fi
	done
}

openvk() {
	local vkurl search
	while [[ ! -z "$1" ]]; do
		search="$search $1"
		shift
	done
	vkurl="https://vk.com/audios361427414?q=$(<<<"$search" eurl | tr -d \')&section=recoms"
		chromium "$vkurl" &>/dev/null &
}

declare -a vkarray
readarray -t vkarray <"${1:-/dev/stdin}"
for i in "${vkarray[@]}"; do openvk "$i"; done
wait $!
echo
