#!/bin/bash

screen -wipe work

(sleep 2 && screen -S work -X select 0 && screen -S work -X kill && screen -S work -X screen) & disown

if ! screen -ls work; then
	screen -dmS work
fi

screen -S work -X chdir /l
screen -S work -X screen
screen -S work -X screen
screen -S work -X screen

(sleep 2 && screen -S work -X select 0) & disown

screen -x work
