'\" t
.\"     Title: __audit_inode
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: January 2017
.\"    Manual: Audit Interfaces
.\"    Source: Kernel Hackers Manual 4.10.0-rc1
.\"  Language: English
.\"
.TH "__AUDIT_INODE" "9" "January 2017" "Kernel Hackers Manual 4\&.10\&" "Audit Interfaces"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
__audit_inode \- store the inode and device from a lookup
.SH "SYNOPSIS"
.HP \w'void\ __audit_inode('u
.BI "void __audit_inode(struct\ filename\ *\ " "name" ", const\ struct\ dentry\ *\ " "dentry" ", unsigned\ int\ " "flags" ");"
.SH "ARGUMENTS"
.PP
\fIname\fR
.RS 4
name being audited
.RE
.PP
\fIdentry\fR
.RS 4
dentry being audited
.RE
.PP
\fIflags\fR
.RS 4
attributes for this particular entry
.RE
.SH "COPYRIGHT"
.br
