'\" t
.\"     Title: __dev_mc_unsync
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: January 2017
.\"    Manual: Network device support
.\"    Source: Kernel Hackers Manual 4.10.0-rc1
.\"  Language: English
.\"
.TH "__DEV_MC_UNSYNC" "9" "January 2017" "Kernel Hackers Manual 4\&.10\&" "Network device support"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
__dev_mc_unsync \- Remove synchronized addresses from device
.SH "SYNOPSIS"
.HP \w'void\ __dev_mc_unsync('u
.BI "void __dev_mc_unsync(struct\ net_device\ *\ " "dev" ", int\ (*" "unsync" ")\ (struct\ net_device\ *,\ const\ unsigned\ char\ *));"
.SH "ARGUMENTS"
.PP
\fIdev\fR
.RS 4
device to sync
.RE
.PP
\fIunsync\fR
.RS 4
function to call if address should be removed
.RE
.SH "DESCRIPTION"
.PP
Remove all addresses that were added to the device by
\fBdev_mc_sync\fR\&.
.SH "COPYRIGHT"
.br
