'\" t
.\"     Title: airq_iv_free
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: January 2017
.\"    Manual: Generic interfaces
.\"    Source: Kernel Hackers Manual 4.10.0-rc1
.\"  Language: English
.\"
.TH "AIRQ_IV_FREE" "9" "January 2017" "Kernel Hackers Manual 4\&.10\&" "Generic interfaces"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
airq_iv_free \- free irq bits of an interrupt vector
.SH "SYNOPSIS"
.HP \w'void\ airq_iv_free('u
.BI "void airq_iv_free(struct\ airq_iv\ *\ " "iv" ", unsigned\ long\ " "bit" ", unsigned\ long\ " "num" ");"
.SH "ARGUMENTS"
.PP
\fIiv\fR
.RS 4
pointer to interrupt vector structure
.RE
.PP
\fIbit\fR
.RS 4
number of the first irq bit to free
.RE
.PP
\fInum\fR
.RS 4
number of consecutive irq bits to free
.RE
.SH "AUTHOR"
.PP
\fBCornelia Huck\fR <\&cornelia.huck@de.ibm.com\&>
.RS 4
Author.
.RE
.SH "COPYRIGHT"
.br
