'\" t
.\"     Title: ata_std_prereset
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: January 2017
.\"    Manual: libata Library
.\"    Source: Kernel Hackers Manual 4.10.0-rc1
.\"  Language: English
.\"
.TH "ATA_STD_PRERESET" "9" "January 2017" "Kernel Hackers Manual 4\&.10\&" "libata Library"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
ata_std_prereset \- prepare for reset
.SH "SYNOPSIS"
.HP \w'int\ ata_std_prereset('u
.BI "int ata_std_prereset(struct\ ata_link\ *\ " "link" ", unsigned\ long\ " "deadline" ");"
.SH "ARGUMENTS"
.PP
\fIlink\fR
.RS 4
ATA link to be reset
.RE
.PP
\fIdeadline\fR
.RS 4
deadline jiffies for the operation
.RE
.SH "DESCRIPTION"
.PP
\fIlink\fR
is about to be reset\&. Initialize it\&. Failure from prereset makes libata abort whole reset sequence and give up that port, so prereset should be best\-effort\&. It does its best to prepare for reset sequence but if things go wrong, it should just whine, not fail\&.
.PP
LOCKING: Kernel thread context (may sleep)
.SH "RETURN"
.PP
0 on success, \-errno otherwise\&.
.SH "AUTHOR"
.PP
\fBJeff Garzik\fR
.RS 4
Author.
.RE
.SH "COPYRIGHT"
.br
