'\" t
.\"     Title: ata_scsi_find_dev
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: January 2017
.\"    Manual: libata SCSI translation/emulation
.\"    Source: Kernel Hackers Manual 4.10.0-rc1
.\"  Language: English
.\"
.TH "ATA_SCSI_FIND_DEV" "9" "January 2017" "Kernel Hackers Manual 4\&.10\&" "libata SCSI translation/emulat"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
ata_scsi_find_dev \- lookup ata_device from scsi_cmnd
.SH "SYNOPSIS"
.HP \w'struct\ ata_device\ *\ ata_scsi_find_dev('u
.BI "struct ata_device * ata_scsi_find_dev(struct\ ata_port\ *\ " "ap" ", const\ struct\ scsi_device\ *\ " "scsidev" ");"
.SH "ARGUMENTS"
.PP
\fIap\fR
.RS 4
ATA port to which the device is attached
.RE
.PP
\fIscsidev\fR
.RS 4
SCSI device from which we derive the ATA device
.RE
.SH "DESCRIPTION"
.PP
Given various information provided in struct scsi_cmnd, map that onto an ATA bus, and using that mapping determine which ata_device is associated with the SCSI command to be sent\&.
.PP
LOCKING: spin_lock_irqsave(host lock)
.SH "RETURN"
.PP
Associated ATA device, or
\fBNULL\fR
if not found\&.
.SH "AUTHOR"
.PP
\fBJeff Garzik\fR
.RS 4
Author.
.RE
.SH "COPYRIGHT"
.br
