'\" t
.\"     Title: bioset_create_nobvec
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: January 2017
.\"    Manual: The Linux VFS
.\"    Source: Kernel Hackers Manual 4.10.0-rc1
.\"  Language: English
.\"
.TH "BIOSET_CREATE_NOBVEC" "9" "January 2017" "Kernel Hackers Manual 4\&.10\&" "The Linux VFS"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
bioset_create_nobvec \- Create a bio_set without bio_vec mempool
.SH "SYNOPSIS"
.HP \w'struct\ bio_set\ *\ bioset_create_nobvec('u
.BI "struct bio_set * bioset_create_nobvec(unsigned\ int\ " "pool_size" ", unsigned\ int\ " "front_pad" ");"
.SH "ARGUMENTS"
.PP
\fIpool_size\fR
.RS 4
Number of bio to cache in the mempool
.RE
.PP
\fIfront_pad\fR
.RS 4
Number of bytes to allocate in front of the returned bio
.RE
.SH "DESCRIPTION"
.PP
Same functionality as
\fBbioset_create\fR
except that mempool is not created for bio_vecs\&. Saving some memory for
\fBbio_clone_fast\fR
users\&.
.SH "COPYRIGHT"
.br
