'\" t
.\"     Title: blk_add_trace_rq
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: January 2017
.\"    Manual: Block Devices
.\"    Source: Kernel Hackers Manual 4.10.0-rc1
.\"  Language: English
.\"
.TH "BLK_ADD_TRACE_RQ" "9" "January 2017" "Kernel Hackers Manual 4\&.10\&" "Block Devices"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
blk_add_trace_rq \- Add a trace for a request oriented action
.SH "SYNOPSIS"
.HP \w'void\ blk_add_trace_rq('u
.BI "void blk_add_trace_rq(struct\ request_queue\ *\ " "q" ", struct\ request\ *\ " "rq" ", unsigned\ int\ " "nr_bytes" ", u32\ " "what" ");"
.SH "ARGUMENTS"
.PP
\fIq\fR
.RS 4
queue the io is for
.RE
.PP
\fIrq\fR
.RS 4
the source request
.RE
.PP
\fInr_bytes\fR
.RS 4
number of completed bytes
.RE
.PP
\fIwhat\fR
.RS 4
the action
.RE
.SH "DESCRIPTION"
.PP
Records an action against a request\&. Will log the bio offset + size\&.
.SH "COPYRIGHT"
.br
