'\" t
.\"     Title: blk_queue_resize_tags
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: January 2017
.\"    Manual: Block Devices
.\"    Source: Kernel Hackers Manual 4.10.0-rc1
.\"  Language: English
.\"
.TH "BLK_QUEUE_RESIZE_TAG" "9" "January 2017" "Kernel Hackers Manual 4\&.10\&" "Block Devices"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
blk_queue_resize_tags \- change the queueing depth
.SH "SYNOPSIS"
.HP \w'int\ blk_queue_resize_tags('u
.BI "int blk_queue_resize_tags(struct\ request_queue\ *\ " "q" ", int\ " "new_depth" ");"
.SH "ARGUMENTS"
.PP
\fIq\fR
.RS 4
the request queue for the device
.RE
.PP
\fInew_depth\fR
.RS 4
the new max command queueing depth
.RE
.SH "NOTES"
.PP
Must be called with the queue lock held\&.
.SH "COPYRIGHT"
.br
