'\" t
.\"     Title: cable_is_40wire
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: January 2017
.\"    Manual: libata Core Internals
.\"    Source: Kernel Hackers Manual 4.10.0-rc1
.\"  Language: English
.\"
.TH "CABLE_IS_40WIRE" "9" "January 2017" "Kernel Hackers Manual 4\&.10\&" "libata Core Internals"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
cable_is_40wire \- 40/80/SATA decider
.SH "SYNOPSIS"
.HP \w'int\ cable_is_40wire('u
.BI "int cable_is_40wire(struct\ ata_port\ *\ " "ap" ");"
.SH "ARGUMENTS"
.PP
\fIap\fR
.RS 4
port to consider
.RE
.SH "DESCRIPTION"
.PP
This function encapsulates the policy for speed management in one place\&. At the moment we don\*(Aqt cache the result but there is a good case for setting ap\->cbl to the result when we are called with unknown cables (and figuring out if it impacts hotplug at all)\&.
.PP
Return 1 if the cable appears to be 40 wire\&.
.SH "AUTHOR"
.PP
\fBJeff Garzik\fR
.RS 4
Author.
.RE
.SH "COPYRIGHT"
.br
