'\" t
.\"     Title: ccw_device_set_offline
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: January 2017
.\"    Manual: The ccw bus
.\"    Source: Kernel Hackers Manual 4.10.0-rc1
.\"  Language: English
.\"
.TH "CCW_DEVICE_SET_OFFLI" "9" "January 2017" "Kernel Hackers Manual 4\&.10\&" "The ccw bus"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
ccw_device_set_offline \- disable a ccw device for I/O
.SH "SYNOPSIS"
.HP \w'int\ ccw_device_set_offline('u
.BI "int ccw_device_set_offline(struct\ ccw_device\ *\ " "cdev" ");"
.SH "ARGUMENTS"
.PP
\fIcdev\fR
.RS 4
target ccw device
.RE
.SH "DESCRIPTION"
.PP
This function calls the driver\*(Aqs
\fBset_offline\fR
function for
\fIcdev\fR, if given, and then disables
\fIcdev\fR\&.
.SH "RETURN"
.PP
\fB0\fR
on success and a negative error value on failure\&.
.SH "CONTEXT"
.PP
enabled, ccw device lock not held
.SH "AUTHOR"
.PP
\fBCornelia Huck\fR <\&cornelia.huck@de.ibm.com\&>
.RS 4
Author.
.RE
.SH "COPYRIGHT"
.br
