'\" t
.\"     Title: crc16
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: January 2017
.\"    Manual: Basic Kernel Library Functions
.\"    Source: Kernel Hackers Manual 4.10.0-rc1
.\"  Language: English
.\"
.TH "CRC16" "9" "January 2017" "Kernel Hackers Manual 4\&.10\&" "Basic Kernel Library Functions"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
crc16 \- compute the CRC\-16 for the data buffer
.SH "SYNOPSIS"
.HP \w'u16\ crc16('u
.BI "u16 crc16(u16\ " "crc" ", u8\ const\ *\ " "buffer" ", size_t\ " "len" ");"
.SH "ARGUMENTS"
.PP
\fIcrc\fR
.RS 4
previous CRC value
.RE
.PP
\fIbuffer\fR
.RS 4
data pointer
.RE
.PP
\fIlen\fR
.RS 4
number of bytes in the buffer
.RE
.SH "DESCRIPTION"
.PP
Returns the updated CRC value\&.
.SH "COPYRIGHT"
.br
