'\" t
.\"     Title: dev_fill_metadata_dst
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: January 2017
.\"    Manual: Network device support
.\"    Source: Kernel Hackers Manual 4.10.0-rc1
.\"  Language: English
.\"
.TH "DEV_FILL_METADATA_DS" "9" "January 2017" "Kernel Hackers Manual 4\&.10\&" "Network device support"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
dev_fill_metadata_dst \- Retrieve tunnel egress information\&.
.SH "SYNOPSIS"
.HP \w'int\ dev_fill_metadata_dst('u
.BI "int dev_fill_metadata_dst(struct\ net_device\ *\ " "dev" ", struct\ sk_buff\ *\ " "skb" ");"
.SH "ARGUMENTS"
.PP
\fIdev\fR
.RS 4
targeted interface
.RE
.PP
\fIskb\fR
.RS 4
The packet\&.
.RE
.SH "DESCRIPTION"
.PP
For better visibility of tunnel traffic OVS needs to retrieve egress tunnel information for a packet\&. Following API allows user to get this info\&.
.SH "COPYRIGHT"
.br
