'\" t
.\"     Title: ether_addr_equal
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: January 2017
.\"    Manual: Network device support
.\"    Source: Kernel Hackers Manual 4.10.0-rc1
.\"  Language: English
.\"
.TH "ETHER_ADDR_EQUAL" "9" "January 2017" "Kernel Hackers Manual 4\&.10\&" "Network device support"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
ether_addr_equal \- Compare two Ethernet addresses
.SH "SYNOPSIS"
.HP \w'bool\ ether_addr_equal('u
.BI "bool ether_addr_equal(const\ u8\ *\ " "addr1" ", const\ u8\ *\ " "addr2" ");"
.SH "ARGUMENTS"
.PP
\fIaddr1\fR
.RS 4
Pointer to a six\-byte array containing the Ethernet address
.RE
.PP
\fIaddr2\fR
.RS 4
Pointer other six\-byte array containing the Ethernet address
.RE
.SH "DESCRIPTION"
.PP
Compare two Ethernet addresses, returns true if equal
.PP
Please note: addr1 & addr2 must both be aligned to u16\&.
.SH "COPYRIGHT"
.br
