'\" t
.\"     Title: fc_remote_port_delete
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: January 2017
.\"    Manual: SCSI mid layer
.\"    Source: Kernel Hackers Manual 4.10.0-rc1
.\"  Language: English
.\"
.TH "FC_REMOTE_PORT_DELET" "9" "January 2017" "Kernel Hackers Manual 4\&.10\&" "SCSI mid layer"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
fc_remote_port_delete \- notifies the fc transport that a remote port is no longer in existence\&.
.SH "SYNOPSIS"
.HP \w'void\ fc_remote_port_delete('u
.BI "void fc_remote_port_delete(struct\ fc_rport\ *\ " "rport" ");"
.SH "ARGUMENTS"
.PP
\fIrport\fR
.RS 4
The remote port that no longer exists
.RE
.SH "DESCRIPTION"
.PP
The LLDD calls this routine to notify the transport that a remote port is no longer part of the topology\&. Note: Although a port may no longer be part of the topology, it may persist in the remote ports displayed by the fc_host\&. We do this under 2 conditions: 1) If the port was a scsi target, we delay its deletion by
\(lqblocking\(rq
it\&. This allows the port to temporarily disappear, then reappear without disrupting the SCSI device tree attached to it\&. During the
\(lqblocked\(rq
period the port will still exist\&. 2) If the port was a scsi target and disappears for longer than we expect, we\*(Aqll delete the port and the tear down the SCSI device tree attached to it\&. However, we want to semi\-persist the target id assigned to that port if it eventually does exist\&. The port structure will remain (although with minimal information) so that the target id bindings remails\&.
.PP
If the remote port is not an FCP Target, it will be fully torn down and deallocated, including the fc_remote_port class device\&.
.PP
If the remote port is an FCP Target, the port will be placed in a temporary blocked state\&. From the LLDD\*(Aqs perspective, the rport no longer exists\&. From the SCSI midlayer\*(Aqs perspective, the SCSI target exists, but all sdevs on it are blocked from further I/O\&. The following is then expected\&.
.PP
If the remote port does not return (signaled by a LLDD call to
\fBfc_remote_port_add\fR) within the dev_loss_tmo timeout, then the scsi target is removed \- killing all outstanding i/o and removing the scsi devices attached ot it\&. The port structure will be marked Not Present and be partially cleared, leaving only enough information to recognize the remote port relative to the scsi target id binding if it later appears\&. The port will remain as long as there is a valid binding (e\&.g\&. until the user changes the binding type or unloads the scsi host with the binding)\&.
.PP
If the remote port returns within the dev_loss_tmo value (and matches according to the target id binding type), the port structure will be reused\&. If it is no longer a SCSI target, the target will be torn down\&. If it continues to be a SCSI target, then the target will be unblocked (allowing i/o to be resumed), and a scan will be activated to ensure that all luns are detected\&.
.PP
Called from normal process context only \- cannot be called from interrupt\&.
.SH "NOTES"
.PP
This routine assumes no locks are held on entry\&.
.SH "AUTHORS"
.PP
\fBJames Bottomley\fR <\&James.Bottomley@hansenpartnership.com\&>
.RS 4
Author.
.RE
.PP
\fBRob Landley\fR <\&rob@landley.net\&>
.RS 4
Author.
.RE
.SH "COPYRIGHT"
.br
