'\" t
.\"     Title: idr_get_next
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: January 2017
.\"    Manual: Basic Kernel Library Functions
.\"    Source: Kernel Hackers Manual 4.10.0-rc1
.\"  Language: English
.\"
.TH "IDR_GET_NEXT" "9" "January 2017" "Kernel Hackers Manual 4\&.10\&" "Basic Kernel Library Functions"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
idr_get_next \- lookup next object of id to given id\&.
.SH "SYNOPSIS"
.HP \w'void\ *\ idr_get_next('u
.BI "void * idr_get_next(struct\ idr\ *\ " "idp" ", int\ *\ " "nextidp" ");"
.SH "ARGUMENTS"
.PP
\fIidp\fR
.RS 4
idr handle
.RE
.PP
\fInextidp\fR
.RS 4
pointer to lookup key
.RE
.SH "DESCRIPTION"
.PP
Returns pointer to registered object with id, which is next number to given id\&. After being looked up, *\fInextidp\fR
will be updated for the next iteration\&.
.PP
This function can be called under
\fBrcu_read_lock\fR, given that the leaf pointers lifetimes are correctly managed\&.
.SH "COPYRIGHT"
.br
