'\" t
.\"     Title: inode_dio_wait
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: January 2017
.\"    Manual: The Linux VFS
.\"    Source: Kernel Hackers Manual 4.10.0-rc1
.\"  Language: English
.\"
.TH "INODE_DIO_WAIT" "9" "January 2017" "Kernel Hackers Manual 4\&.10\&" "The Linux VFS"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
inode_dio_wait \- wait for outstanding DIO requests to finish
.SH "SYNOPSIS"
.HP \w'void\ inode_dio_wait('u
.BI "void inode_dio_wait(struct\ inode\ *\ " "inode" ");"
.SH "ARGUMENTS"
.PP
\fIinode\fR
.RS 4
inode to wait for
.RE
.SH "DESCRIPTION"
.PP
Waits for all pending direct I/O requests to finish so that we can proceed with a truncate or equivalent operation\&.
.PP
Must be called under a lock that serializes taking new references to i_dio_count, usually by inode\->i_mutex\&.
.SH "COPYRIGHT"
.br
