'\" t
.\"     Title: ipc_alloc
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: January 2017
.\"    Manual: Kernel IPC facilities
.\"    Source: Kernel Hackers Manual 4.10.0-rc1
.\"  Language: English
.\"
.TH "IPC_ALLOC" "9" "January 2017" "Kernel Hackers Manual 4\&.10\&" "Kernel IPC facilities"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
ipc_alloc \- allocate ipc space
.SH "SYNOPSIS"
.HP \w'void\ *\ ipc_alloc('u
.BI "void * ipc_alloc(int\ " "size" ");"
.SH "ARGUMENTS"
.PP
\fIsize\fR
.RS 4
size desired
.RE
.SH "DESCRIPTION"
.PP
Allocate memory from the appropriate pools and return a pointer to it\&. NULL is returned if the allocation fails
.SH "COPYRIGHT"
.br
