'\" t
.\"     Title: irq_chip_set_affinity_parent
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: January 2017
.\"    Manual: Internal Functions Provided
.\"    Source: Kernel Hackers Manual 4.10.0-rc1
.\"  Language: English
.\"
.TH "IRQ_CHIP_SET_AFFINIT" "9" "January 2017" "Kernel Hackers Manual 4\&.10\&" "Internal Functions Provided"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
irq_chip_set_affinity_parent \- Set affinity on the parent interrupt
.SH "SYNOPSIS"
.HP \w'int\ irq_chip_set_affinity_parent('u
.BI "int irq_chip_set_affinity_parent(struct\ irq_data\ *\ " "data" ", const\ struct\ cpumask\ *\ " "dest" ", bool\ " "force" ");"
.SH "ARGUMENTS"
.PP
\fIdata\fR
.RS 4
Pointer to interrupt specific data
.RE
.PP
\fIdest\fR
.RS 4
The affinity mask to set
.RE
.PP
\fIforce\fR
.RS 4
Flag to enforce setting (disable online checks)
.RE
.SH "DESCRIPTION"
.PP
Conditinal, as the underlying parent chip might not implement it\&.
.SH "AUTHORS"
.PP
\fBThomas Gleixner\fR <\&tglx@linutronix.de\&>
.RS 4
Author.
.RE
.PP
\fBIngo Molnar\fR <\&mingo@elte.hu\&>
.RS 4
Author.
.RE
.SH "COPYRIGHT"
.br
