'\" t
.\"     Title: iscsi_find_flashnode_conn
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: January 2017
.\"    Manual: SCSI mid layer
.\"    Source: Kernel Hackers Manual 4.10.0-rc1
.\"  Language: English
.\"
.TH "ISCSI_FIND_FLASHNODE" "9" "January 2017" "Kernel Hackers Manual 4\&.10\&" "SCSI mid layer"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
iscsi_find_flashnode_conn \- finds flashnode connection entry
.SH "SYNOPSIS"
.HP \w'struct\ device\ *\ iscsi_find_flashnode_conn('u
.BI "struct device * iscsi_find_flashnode_conn(struct\ iscsi_bus_flash_session\ *\ " "fnode_sess" ");"
.SH "ARGUMENTS"
.PP
\fIfnode_sess\fR
.RS 4
pointer to parent flashnode session entry
.RE
.SH "DESCRIPTION"
.PP
Finds the flashnode connection object comparing the data passed using logic defined in passed function pointer
.SH "RETURN"
.PP
pointer to found flashnode connection device object on success
\fBNULL\fR
on failure
.SH "AUTHORS"
.PP
\fBJames Bottomley\fR <\&James.Bottomley@hansenpartnership.com\&>
.RS 4
Author.
.RE
.PP
\fBRob Landley\fR <\&rob@landley.net\&>
.RS 4
Author.
.RE
.SH "COPYRIGHT"
.br
