'\" t
.\"     Title: iterate_supers_type
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: January 2017
.\"    Manual: The Linux VFS
.\"    Source: Kernel Hackers Manual 4.10.0-rc1
.\"  Language: English
.\"
.TH "ITERATE_SUPERS_TYPE" "9" "January 2017" "Kernel Hackers Manual 4\&.10\&" "The Linux VFS"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
iterate_supers_type \- call function for superblocks of given type
.SH "SYNOPSIS"
.HP \w'void\ iterate_supers_type('u
.BI "void iterate_supers_type(struct\ file_system_type\ *\ " "type" ", void\ (*" "f" ")\ (struct\ super_block\ *,\ void\ *), void\ *\ " "arg" ");"
.SH "ARGUMENTS"
.PP
\fItype\fR
.RS 4
fs type
.RE
.PP
\fIf\fR
.RS 4
function to call
.RE
.PP
\fIarg\fR
.RS 4
argument to pass to it
.RE
.SH "DESCRIPTION"
.PP
Scans the superblock list and calls given function, passing it locked superblock and given argument\&.
.SH "COPYRIGHT"
.br
