'\" t
.\"     Title: memchr_inv
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: January 2017
.\"    Manual: Basic C Library Functions
.\"    Source: Kernel Hackers Manual 4.10.0-rc1
.\"  Language: English
.\"
.TH "MEMCHR_INV" "9" "January 2017" "Kernel Hackers Manual 4\&.10\&" "Basic C Library Functions"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
memchr_inv \- Find an unmatching character in an area of memory\&.
.SH "SYNOPSIS"
.HP \w'void\ *\ memchr_inv('u
.BI "void * memchr_inv(const\ void\ *\ " "start" ", int\ " "c" ", size_t\ " "bytes" ");"
.SH "ARGUMENTS"
.PP
\fIstart\fR
.RS 4
The memory area
.RE
.PP
\fIc\fR
.RS 4
Find a character other than c
.RE
.PP
\fIbytes\fR
.RS 4
The size of the area\&.
.RE
.SH "DESCRIPTION"
.PP
returns the address of the first character other than
\fIc\fR, or
\fBNULL\fR
if the whole buffer contains just
\fIc\fR\&.
.SH "COPYRIGHT"
.br
