'\" t
.\"     Title: nand_read
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: January 2017
.\"    Manual: Internal Functions Provided
.\"    Source: Kernel Hackers Manual 4.10.0-rc1
.\"  Language: English
.\"
.TH "NAND_READ" "9" "January 2017" "Kernel Hackers Manual 4\&.10\&" "Internal Functions Provided"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
nand_read \- [MTD Interface] MTD compatibility function for nand_do_read_ecc
.SH "SYNOPSIS"
.HP \w'int\ nand_read('u
.BI "int nand_read(struct\ mtd_info\ *\ " "mtd" ", loff_t\ " "from" ", size_t\ " "len" ", size_t\ *\ " "retlen" ", uint8_t\ *\ " "buf" ");"
.SH "ARGUMENTS"
.PP
\fImtd\fR
.RS 4
MTD device structure
.RE
.PP
\fIfrom\fR
.RS 4
offset to read from
.RE
.PP
\fIlen\fR
.RS 4
number of bytes to read
.RE
.PP
\fIretlen\fR
.RS 4
pointer to variable to store the number of read bytes
.RE
.PP
\fIbuf\fR
.RS 4
the databuffer to put data
.RE
.SH "DESCRIPTION"
.PP
Get hold of the chip and call nand_do_read\&.
.SH "AUTHOR"
.PP
\fBThomas Gleixner\fR <\&tglx@linutronix.de\&>
.RS 4
Author.
.RE
.SH "COPYRIGHT"
.br
