'\" t
.\"     Title: panic_nand_get_device
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: January 2017
.\"    Manual: Internal Functions Provided
.\"    Source: Kernel Hackers Manual 4.10.0-rc1
.\"  Language: English
.\"
.TH "PANIC_NAND_GET_DEVIC" "9" "January 2017" "Kernel Hackers Manual 4\&.10\&" "Internal Functions Provided"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
panic_nand_get_device \- [GENERIC] Get chip for selected access
.SH "SYNOPSIS"
.HP \w'void\ panic_nand_get_device('u
.BI "void panic_nand_get_device(struct\ nand_chip\ *\ " "chip" ", struct\ mtd_info\ *\ " "mtd" ", int\ " "new_state" ");"
.SH "ARGUMENTS"
.PP
\fIchip\fR
.RS 4
the nand chip descriptor
.RE
.PP
\fImtd\fR
.RS 4
MTD device structure
.RE
.PP
\fInew_state\fR
.RS 4
the state which is requested
.RE
.SH "DESCRIPTION"
.PP
Used when in panic, no locks are taken\&.
.SH "AUTHOR"
.PP
\fBThomas Gleixner\fR <\&tglx@linutronix.de\&>
.RS 4
Author.
.RE
.SH "COPYRIGHT"
.br
