'\" t
.\"     Title: pci_set_pcie_reset_state
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: January 2017
.\"    Manual: Hardware Interfaces
.\"    Source: Kernel Hackers Manual 4.10.0-rc1
.\"  Language: English
.\"
.TH "PCI_SET_PCIE_RESET_S" "9" "January 2017" "Kernel Hackers Manual 4\&.10\&" "Hardware Interfaces"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
pci_set_pcie_reset_state \- set reset state for device dev
.SH "SYNOPSIS"
.HP \w'int\ pci_set_pcie_reset_state('u
.BI "int pci_set_pcie_reset_state(struct\ pci_dev\ *\ " "dev" ", enum\ pcie_reset_state\ " "state" ");"
.SH "ARGUMENTS"
.PP
\fIdev\fR
.RS 4
the PCIe device reset
.RE
.PP
\fIstate\fR
.RS 4
Reset state to enter into
.RE
.SH "DESCRIPTION"
.PP
.PP
Sets the PCI reset state for the device\&.
.SH "COPYRIGHT"
.br
