'\" t
.\"     Title: pci_write_rom
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: January 2017
.\"    Manual: Hardware Interfaces
.\"    Source: Kernel Hackers Manual 4.10.0-rc1
.\"  Language: English
.\"
.TH "PCI_WRITE_ROM" "9" "January 2017" "Kernel Hackers Manual 4\&.10\&" "Hardware Interfaces"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
pci_write_rom \- used to enable access to the PCI ROM display
.SH "SYNOPSIS"
.HP \w'ssize_t\ pci_write_rom('u
.BI "ssize_t pci_write_rom(struct\ file\ *\ " "filp" ", struct\ kobject\ *\ " "kobj" ", struct\ bin_attribute\ *\ " "bin_attr" ", char\ *\ " "buf" ", loff_t\ " "off" ", size_t\ " "count" ");"
.SH "ARGUMENTS"
.PP
\fIfilp\fR
.RS 4
sysfs file
.RE
.PP
\fIkobj\fR
.RS 4
kernel object handle
.RE
.PP
\fIbin_attr\fR
.RS 4
struct bin_attribute for this file
.RE
.PP
\fIbuf\fR
.RS 4
user input
.RE
.PP
\fIoff\fR
.RS 4
file offset
.RE
.PP
\fIcount\fR
.RS 4
number of byte in input
.RE
.SH "DESCRIPTION"
.PP
writing anything except 0 enables it
.SH "COPYRIGHT"
.br
