'\" t
.\"     Title: pci_scan_slot
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: January 2017
.\"    Manual: Hardware Interfaces
.\"    Source: Kernel Hackers Manual 4.10.0-rc1
.\"  Language: English
.\"
.TH "PCI_SCAN_SLOT" "9" "January 2017" "Kernel Hackers Manual 4\&.10\&" "Hardware Interfaces"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
pci_scan_slot \- scan a PCI slot on a bus for devices\&.
.SH "SYNOPSIS"
.HP \w'int\ pci_scan_slot('u
.BI "int pci_scan_slot(struct\ pci_bus\ *\ " "bus" ", int\ " "devfn" ");"
.SH "ARGUMENTS"
.PP
\fIbus\fR
.RS 4
PCI bus to scan
.RE
.PP
\fIdevfn\fR
.RS 4
slot number to scan (must have zero function\&.)
.RE
.SH "DESCRIPTION"
.PP
Scan a PCI slot on the specified PCI bus for devices, adding discovered devices to the
\fIbus\fR\->devices list\&. New devices will not have is_added set\&.
.PP
Returns the number of new devices found\&.
.SH "COPYRIGHT"
.br
