'\" t
.\"     Title: pci_find_parent_resource
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: January 2017
.\"    Manual: Hardware Interfaces
.\"    Source: Kernel Hackers Manual 4.10.0-rc1
.\"  Language: English
.\"
.TH "PCI_FIND_PARENT_RESO" "9" "January 2017" "Kernel Hackers Manual 4\&.10\&" "Hardware Interfaces"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
pci_find_parent_resource \- return resource region of parent bus of given region
.SH "SYNOPSIS"
.HP \w'struct\ resource\ *\ pci_find_parent_resource('u
.BI "struct resource * pci_find_parent_resource(const\ struct\ pci_dev\ *\ " "dev" ", struct\ resource\ *\ " "res" ");"
.SH "ARGUMENTS"
.PP
\fIdev\fR
.RS 4
PCI device structure contains resources to be searched
.RE
.PP
\fIres\fR
.RS 4
child resource record for which parent is sought
.RE
.SH "DESCRIPTION"
.PP
For given resource region of given device, return the resource region of parent bus the given region is contained in\&.
.SH "COPYRIGHT"
.br
