'\" t
.\"     Title: pci_set_power_state
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: January 2017
.\"    Manual: Hardware Interfaces
.\"    Source: Kernel Hackers Manual 4.10.0-rc1
.\"  Language: English
.\"
.TH "PCI_SET_POWER_STATE" "9" "January 2017" "Kernel Hackers Manual 4\&.10\&" "Hardware Interfaces"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
pci_set_power_state \- Set the power state of a PCI device
.SH "SYNOPSIS"
.HP \w'int\ pci_set_power_state('u
.BI "int pci_set_power_state(struct\ pci_dev\ *\ " "dev" ", pci_power_t\ " "state" ");"
.SH "ARGUMENTS"
.PP
\fIdev\fR
.RS 4
PCI device to handle\&.
.RE
.PP
\fIstate\fR
.RS 4
PCI power state (D0, D1, D2, D3hot) to put the device into\&.
.RE
.SH "DESCRIPTION"
.PP
Transition a device to a new power state, using the platform firmware and/or the device\*(Aqs PCI PM registers\&.
.PP
RETURN VALUE: \-EINVAL if the requested state is invalid\&. \-EIO if device does not support PCI PM or its PM capabilities register has a wrong version, or device doesn\*(Aqt support the requested state\&. 0 if device already is in the requested state\&. 0 if device\*(Aqs power state has been successfully changed\&.
.SH "COPYRIGHT"
.br
