'\" t
.\"     Title: pci_find_ext_capability
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: January 2017
.\"    Manual: Hardware Interfaces
.\"    Source: Kernel Hackers Manual 4.10.0-rc1
.\"  Language: English
.\"
.TH "PCI_FIND_EXT_CAPABIL" "9" "January 2017" "Kernel Hackers Manual 4\&.10\&" "Hardware Interfaces"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
pci_find_ext_capability \- Find an extended capability
.SH "SYNOPSIS"
.HP \w'int\ pci_find_ext_capability('u
.BI "int pci_find_ext_capability(struct\ pci_dev\ *\ " "dev" ", int\ " "cap" ");"
.SH "ARGUMENTS"
.PP
\fIdev\fR
.RS 4
PCI device to query
.RE
.PP
\fIcap\fR
.RS 4
capability code
.RE
.SH "DESCRIPTION"
.PP
Returns the address of the requested extended capability structure within the device\*(Aqs PCI configuration space or 0 if the device does not support it\&. Possible values for
\fIcap\fR:
.PP
\fBPCI_EXT_CAP_ID_ERR\fR
Advanced Error Reporting
\fBPCI_EXT_CAP_ID_VC\fR
Virtual Channel
\fBPCI_EXT_CAP_ID_DSN\fR
Device Serial Number
\fBPCI_EXT_CAP_ID_PWR\fR
Power Budgeting
.SH "COPYRIGHT"
.br
