'\" t
.\"     Title: pci_find_next_ht_capability
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: January 2017
.\"    Manual: Hardware Interfaces
.\"    Source: Kernel Hackers Manual 4.10.0-rc1
.\"  Language: English
.\"
.TH "PCI_FIND_NEXT_HT_CAP" "9" "January 2017" "Kernel Hackers Manual 4\&.10\&" "Hardware Interfaces"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
pci_find_next_ht_capability \- query a device\*(Aqs Hypertransport capabilities
.SH "SYNOPSIS"
.HP \w'int\ pci_find_next_ht_capability('u
.BI "int pci_find_next_ht_capability(struct\ pci_dev\ *\ " "dev" ", int\ " "pos" ", int\ " "ht_cap" ");"
.SH "ARGUMENTS"
.PP
\fIdev\fR
.RS 4
PCI device to query
.RE
.PP
\fIpos\fR
.RS 4
Position from which to continue searching
.RE
.PP
\fIht_cap\fR
.RS 4
Hypertransport capability code
.RE
.SH "DESCRIPTION"
.PP
To be used in conjunction with
\fBpci_find_ht_capability\fR
to search for all capabilities matching
\fIht_cap\fR\&.
\fIpos\fR
should always be a value returned from
\fBpci_find_ht_capability\fR\&.
.PP
NB\&. To be 100% safe against broken PCI devices, the caller should take steps to avoid an infinite loop\&.
.SH "COPYRIGHT"
.br
