'\" t
.\"     Title: phy_attach_direct
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: January 2017
.\"    Manual: Network device support
.\"    Source: Kernel Hackers Manual 4.10.0-rc1
.\"  Language: English
.\"
.TH "PHY_ATTACH_DIRECT" "9" "January 2017" "Kernel Hackers Manual 4\&.10\&" "Network device support"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
phy_attach_direct \- attach a network device to a given PHY device pointer
.SH "SYNOPSIS"
.HP \w'int\ phy_attach_direct('u
.BI "int phy_attach_direct(struct\ net_device\ *\ " "dev" ", struct\ phy_device\ *\ " "phydev" ", u32\ " "flags" ", phy_interface_t\ " "interface" ");"
.SH "ARGUMENTS"
.PP
\fIdev\fR
.RS 4
network device to attach
.RE
.PP
\fIphydev\fR
.RS 4
Pointer to phy_device to attach
.RE
.PP
\fIflags\fR
.RS 4
PHY device\*(Aqs dev_flags
.RE
.PP
\fIinterface\fR
.RS 4
PHY device\*(Aqs interface
.RE
.SH "DESCRIPTION"
.PP
Called by drivers to attach to a particular PHY device\&. The phy_device is found, and properly hooked up to the phy_driver\&. If no driver is attached, then a generic driver is used\&. The phy_device is given a ptr to the attaching device, and given a callback for link status change\&. The phy_device is returned to the attaching driver\&. This function takes a reference on the phy device\&.
.SH "COPYRIGHT"
.br
