'\" t
.\"     Title: relay_close_buf
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: January 2017
.\"    Manual: relay interface support
.\"    Source: Kernel Hackers Manual 4.10.0-rc1
.\"  Language: English
.\"
.TH "RELAY_CLOSE_BUF" "9" "January 2017" "Kernel Hackers Manual 4\&.10\&" "relay interface support"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
relay_close_buf \- close a channel buffer
.SH "SYNOPSIS"
.HP \w'void\ relay_close_buf('u
.BI "void relay_close_buf(struct\ rchan_buf\ *\ " "buf" ");"
.SH "ARGUMENTS"
.PP
\fIbuf\fR
.RS 4
channel buffer
.RE
.SH "DESCRIPTION"
.PP
Marks the buffer finalized and restores the default callbacks\&. The channel buffer and channel buffer data structure are then freed automatically when the last reference is given up\&.
.SH "COPYRIGHT"
.br
