'\" t
.\"     Title: rio_disc_peer
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: January 2017
.\"    Manual: Internals
.\"    Source: Kernel Hackers Manual 4.10.0-rc1
.\"  Language: English
.\"
.TH "RIO_DISC_PEER" "9" "January 2017" "Kernel Hackers Manual 4\&.10\&" "Internals"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
rio_disc_peer \- Recursively discovers a RIO network through a master port
.SH "SYNOPSIS"
.HP \w'int\ rio_disc_peer('u
.BI "int rio_disc_peer(struct\ rio_net\ *\ " "net" ", struct\ rio_mport\ *\ " "port" ", u16\ " "destid" ", u8\ " "hopcount" ", struct\ rio_dev\ *\ " "prev" ", int\ " "prev_port" ");"
.SH "ARGUMENTS"
.PP
\fInet\fR
.RS 4
RIO network being discovered
.RE
.PP
\fIport\fR
.RS 4
Master port to send transactions
.RE
.PP
\fIdestid\fR
.RS 4
Current destination ID in network
.RE
.PP
\fIhopcount\fR
.RS 4
Number of hops into the network
.RE
.PP
\fIprev\fR
.RS 4
previous rio_dev
.RE
.PP
\fIprev_port\fR
.RS 4
previous port number
.RE
.SH "DESCRIPTION"
.PP
Recursively discovers a RIO network\&. Transactions are sent via the master port passed in
\fIport\fR\&.
.SH "AUTHOR"
.PP
\fBMatt Porter\fR <\&mporter@kernel.crashing.org\&>, <\&mporter@mvista.com\&>
.RS 4
Author.
.RE
.SH "COPYRIGHT"
.br
