'\" t
.\"     Title: rio_add_device
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: January 2017
.\"    Manual: RapidIO driver interface
.\"    Source: Kernel Hackers Manual 4.10.0-rc1
.\"  Language: English
.\"
.TH "RIO_ADD_DEVICE" "9" "January 2017" "Kernel Hackers Manual 4\&.10\&" "RapidIO driver interface"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
rio_add_device \- Adds a RIO device to the device model
.SH "SYNOPSIS"
.HP \w'int\ rio_add_device('u
.BI "int rio_add_device(struct\ rio_dev\ *\ " "rdev" ");"
.SH "ARGUMENTS"
.PP
\fIrdev\fR
.RS 4
RIO device
.RE
.SH "DESCRIPTION"
.PP
Adds the RIO device to the global device list and adds the RIO device to the RIO device list\&. Creates the generic sysfs nodes for an RIO device\&.
.SH "AUTHOR"
.PP
\fBMatt Porter\fR <\&mporter@kernel.crashing.org\&>, <\&mporter@mvista.com\&>
.RS 4
Author.
.RE
.SH "COPYRIGHT"
.br
