'\" t
.\"     Title: rio_match_bus
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: January 2017
.\"    Manual: Internals
.\"    Source: Kernel Hackers Manual 4.10.0-rc1
.\"  Language: English
.\"
.TH "RIO_MATCH_BUS" "9" "January 2017" "Kernel Hackers Manual 4\&.10\&" "Internals"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
rio_match_bus \- Tell if a RIO device structure has a matching RIO driver device id structure
.SH "SYNOPSIS"
.HP \w'int\ rio_match_bus('u
.BI "int rio_match_bus(struct\ device\ *\ " "dev" ", struct\ device_driver\ *\ " "drv" ");"
.SH "ARGUMENTS"
.PP
\fIdev\fR
.RS 4
the standard device structure to match against
.RE
.PP
\fIdrv\fR
.RS 4
the standard driver structure containing the ids to match against
.RE
.SH "DESCRIPTION"
.PP
Used by a driver to check whether a RIO device present in the system is in its list of supported devices\&. Returns 1 if there is a matching
struct rio_device_id
or 0 if there is no match\&.
.SH "AUTHOR"
.PP
\fBMatt Porter\fR <\&mporter@kernel.crashing.org\&>, <\&mporter@mvista.com\&>
.RS 4
Author.
.RE
.SH "COPYRIGHT"
.br
