'\" t
.\"     Title: rio_route_clr_table
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: January 2017
.\"    Manual: RapidIO driver interface
.\"    Source: Kernel Hackers Manual 4.10.0-rc1
.\"  Language: English
.\"
.TH "RIO_ROUTE_CLR_TABLE" "9" "January 2017" "Kernel Hackers Manual 4\&.10\&" "RapidIO driver interface"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
rio_route_clr_table \- Clear a switch routing table
.SH "SYNOPSIS"
.HP \w'int\ rio_route_clr_table('u
.BI "int rio_route_clr_table(struct\ rio_dev\ *\ " "rdev" ", u16\ " "table" ", int\ " "lock" ");"
.SH "ARGUMENTS"
.PP
\fIrdev\fR
.RS 4
RIO device
.RE
.PP
\fItable\fR
.RS 4
Routing table ID
.RE
.PP
\fIlock\fR
.RS 4
apply a hardware lock on switch device flag (1=lock, 0=no_lock)
.RE
.SH "DESCRIPTION"
.PP
If available calls the switch specific
\fBclr_table\fR
method to clear a switch routing table\&. Otherwise uses standard RT write method as defined by RapidIO specification\&. A specific routing table can be selected using the
\fItable\fR
argument if a switch has per port routing tables or the standard (or global) table may be used by passing
\fBRIO_GLOBAL_TABLE\fR
in
\fItable\fR\&.
.PP
Returns
\fB0\fR
on success or
\fB\-EINVAL\fR
on failure\&.
.SH "AUTHOR"
.PP
\fBMatt Porter\fR <\&mporter@kernel.crashing.org\&>, <\&mporter@mvista.com\&>
.RS 4
Author.
.RE
.SH "COPYRIGHT"
.br
