'\" t
.\"     Title: scsi_device_quiesce
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: January 2017
.\"    Manual: SCSI mid layer
.\"    Source: Kernel Hackers Manual 4.10.0-rc1
.\"  Language: English
.\"
.TH "SCSI_DEVICE_QUIESCE" "9" "January 2017" "Kernel Hackers Manual 4\&.10\&" "SCSI mid layer"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
scsi_device_quiesce \- Block user issued commands\&.
.SH "SYNOPSIS"
.HP \w'int\ scsi_device_quiesce('u
.BI "int scsi_device_quiesce(struct\ scsi_device\ *\ " "sdev" ");"
.SH "ARGUMENTS"
.PP
\fIsdev\fR
.RS 4
scsi device to quiesce\&.
.RE
.SH "DESCRIPTION"
.PP
This works by trying to transition to the SDEV_QUIESCE state (which must be a legal transition)\&. When the device is in this state, only special requests will be accepted, all others will be deferred\&. Since special requests may also be requeued requests, a successful return doesn\*(Aqt guarantee the device will be totally quiescent\&.
.PP
Must be called with user context, may sleep\&.
.PP
Returns zero if unsuccessful or an error if not\&.
.SH "AUTHORS"
.PP
\fBJames Bottomley\fR <\&James.Bottomley@hansenpartnership.com\&>
.RS 4
Author.
.RE
.PP
\fBRob Landley\fR <\&rob@landley.net\&>
.RS 4
Author.
.RE
.SH "COPYRIGHT"
.br
