'\" t
.\"     Title: scsi_eh_finish_cmd
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: January 2017
.\"    Manual: SCSI mid layer
.\"    Source: Kernel Hackers Manual 4.10.0-rc1
.\"  Language: English
.\"
.TH "SCSI_EH_FINISH_CMD" "9" "January 2017" "Kernel Hackers Manual 4\&.10\&" "SCSI mid layer"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
scsi_eh_finish_cmd \- Handle a cmd that eh is finished with\&.
.SH "SYNOPSIS"
.HP \w'void\ scsi_eh_finish_cmd('u
.BI "void scsi_eh_finish_cmd(struct\ scsi_cmnd\ *\ " "scmd" ", struct\ list_head\ *\ " "done_q" ");"
.SH "ARGUMENTS"
.PP
\fIscmd\fR
.RS 4
Original SCSI cmd that eh has finished\&.
.RE
.PP
\fIdone_q\fR
.RS 4
Queue for processed commands\&.
.RE
.SH "NOTES"
.PP
We don\*(Aqt want to use the normal command completion while we are are still handling errors \- it may cause other commands to be queued, and that would disturb what we are doing\&. Thus we really want to keep a list of pending commands for final completion, and once we are ready to leave error handling we handle completion for real\&.
.SH "AUTHORS"
.PP
\fBJames Bottomley\fR <\&James.Bottomley@hansenpartnership.com\&>
.RS 4
Author.
.RE
.PP
\fBRob Landley\fR <\&rob@landley.net\&>
.RS 4
Author.
.RE
.SH "COPYRIGHT"
.br
