'\" t
.\"     Title: sdev_evt_send
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: January 2017
.\"    Manual: SCSI mid layer
.\"    Source: Kernel Hackers Manual 4.10.0-rc1
.\"  Language: English
.\"
.TH "SDEV_EVT_SEND" "9" "January 2017" "Kernel Hackers Manual 4\&.10\&" "SCSI mid layer"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
sdev_evt_send \- send asserted event to uevent thread
.SH "SYNOPSIS"
.HP \w'void\ sdev_evt_send('u
.BI "void sdev_evt_send(struct\ scsi_device\ *\ " "sdev" ", struct\ scsi_event\ *\ " "evt" ");"
.SH "ARGUMENTS"
.PP
\fIsdev\fR
.RS 4
scsi_device event occurred on
.RE
.PP
\fIevt\fR
.RS 4
event to send
.RE
.SH "DESCRIPTION"
.PP
Assert scsi device event asynchronously\&.
.SH "AUTHORS"
.PP
\fBJames Bottomley\fR <\&James.Bottomley@hansenpartnership.com\&>
.RS 4
Author.
.RE
.PP
\fBRob Landley\fR <\&rob@landley.net\&>
.RS 4
Author.
.RE
.SH "COPYRIGHT"
.br
