'\" t
.\"     Title: skb_unlink
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: January 2017
.\"    Manual: Linux Networking
.\"    Source: Kernel Hackers Manual 4.10.0-rc1
.\"  Language: English
.\"
.TH "SKB_UNLINK" "9" "January 2017" "Kernel Hackers Manual 4\&.10\&" "Linux Networking"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
skb_unlink \- remove a buffer from a list
.SH "SYNOPSIS"
.HP \w'void\ skb_unlink('u
.BI "void skb_unlink(struct\ sk_buff\ *\ " "skb" ", struct\ sk_buff_head\ *\ " "list" ");"
.SH "ARGUMENTS"
.PP
\fIskb\fR
.RS 4
buffer to remove
.RE
.PP
\fIlist\fR
.RS 4
list to use
.RE
.SH "DESCRIPTION"
.PP
Remove a packet from a list\&. The list locks are taken and this function is atomic with respect to other list locked calls
.PP
You must know what list the SKB is on\&.
.SH "COPYRIGHT"
.br
