'\" t
.\"     Title: skb_trim
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: January 2017
.\"    Manual: Linux Networking
.\"    Source: Kernel Hackers Manual 4.10.0-rc1
.\"  Language: English
.\"
.TH "SKB_TRIM" "9" "January 2017" "Kernel Hackers Manual 4\&.10\&" "Linux Networking"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
skb_trim \- remove end from a buffer
.SH "SYNOPSIS"
.HP \w'void\ skb_trim('u
.BI "void skb_trim(struct\ sk_buff\ *\ " "skb" ", unsigned\ int\ " "len" ");"
.SH "ARGUMENTS"
.PP
\fIskb\fR
.RS 4
buffer to alter
.RE
.PP
\fIlen\fR
.RS 4
new length
.RE
.SH "DESCRIPTION"
.PP
Cut the length of a buffer down by removing data from the tail\&. If the buffer is already under the length specified it is not modified\&. The skb must be linear\&.
.SH "COPYRIGHT"
.br
