'\" t
.\"     Title: splice_direct_to_actor
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: January 2017
.\"    Manual: splice API
.\"    Source: Kernel Hackers Manual 4.10.0-rc1
.\"  Language: English
.\"
.TH "SPLICE_DIRECT_TO_ACT" "9" "January 2017" "Kernel Hackers Manual 4\&.10\&" "splice API"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
splice_direct_to_actor \- splices data directly between two non\-pipes
.SH "SYNOPSIS"
.HP \w'ssize_t\ splice_direct_to_actor('u
.BI "ssize_t splice_direct_to_actor(struct\ file\ *\ " "in" ", struct\ splice_desc\ *\ " "sd" ", splice_direct_actor\ *\ " "actor" ");"
.SH "ARGUMENTS"
.PP
\fIin\fR
.RS 4
file to splice from
.RE
.PP
\fIsd\fR
.RS 4
actor information on where to splice to
.RE
.PP
\fIactor\fR
.RS 4
handles the data splicing
.RE
.SH "DESCRIPTION"
.PP
This is a special case helper to splice directly between two points, without requiring an explicit pipe\&. Internally an allocated pipe is cached in the process, and reused during the lifetime of that process\&.
.SH "COPYRIGHT"
.br
