'\" t
.\"     Title: srp_tmo_valid
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: January 2017
.\"    Manual: SCSI mid layer
.\"    Source: Kernel Hackers Manual 4.10.0-rc1
.\"  Language: English
.\"
.TH "SRP_TMO_VALID" "9" "January 2017" "Kernel Hackers Manual 4\&.10\&" "SCSI mid layer"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
srp_tmo_valid \- check timeout combination validity
.SH "SYNOPSIS"
.HP \w'int\ srp_tmo_valid('u
.BI "int srp_tmo_valid(int\ " "reconnect_delay" ", int\ " "fast_io_fail_tmo" ", int\ " "dev_loss_tmo" ");"
.SH "ARGUMENTS"
.PP
\fIreconnect_delay\fR
.RS 4
Reconnect delay in seconds\&.
.RE
.PP
\fIfast_io_fail_tmo\fR
.RS 4
Fast I/O fail timeout in seconds\&.
.RE
.PP
\fIdev_loss_tmo\fR
.RS 4
Device loss timeout in seconds\&.
.RE
.SH "DESCRIPTION"
.PP
The combination of the timeout parameters must be such that SCSI commands are finished in a reasonable time\&. Hence do not allow the fast I/O fail timeout to exceed SCSI_DEVICE_BLOCK_MAX_TIMEOUT nor allow dev_loss_tmo to exceed that limit if failing I/O fast has been disabled\&. Furthermore, these parameters must be such that multipath can detect failed paths timely\&. Hence do not allow all three parameters to be disabled simultaneously\&.
.SH "AUTHORS"
.PP
\fBJames Bottomley\fR <\&James.Bottomley@hansenpartnership.com\&>
.RS 4
Author.
.RE
.PP
\fBRob Landley\fR <\&rob@landley.net\&>
.RS 4
Author.
.RE
.SH "COPYRIGHT"
.br
