'\" t
.\"     Title: strncmp
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: January 2017
.\"    Manual: Basic C Library Functions
.\"    Source: Kernel Hackers Manual 4.10.0-rc1
.\"  Language: English
.\"
.TH "STRNCMP" "9" "January 2017" "Kernel Hackers Manual 4\&.10\&" "Basic C Library Functions"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
strncmp \- Compare two length\-limited strings
.SH "SYNOPSIS"
.HP \w'int\ strncmp('u
.BI "int strncmp(const\ char\ *\ " "cs" ", const\ char\ *\ " "ct" ", size_t\ " "count" ");"
.SH "ARGUMENTS"
.PP
\fIcs\fR
.RS 4
One string
.RE
.PP
\fIct\fR
.RS 4
Another string
.RE
.PP
\fIcount\fR
.RS 4
The maximum number of bytes to compare
.RE
.SH "COPYRIGHT"
.br
