'\" t
.\"     Title: strsep
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: January 2017
.\"    Manual: Basic C Library Functions
.\"    Source: Kernel Hackers Manual 4.10.0-rc1
.\"  Language: English
.\"
.TH "STRSEP" "9" "January 2017" "Kernel Hackers Manual 4\&.10\&" "Basic C Library Functions"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
strsep \- Split a string into tokens
.SH "SYNOPSIS"
.HP \w'char\ *\ strsep('u
.BI "char * strsep(char\ **\ " "s" ", const\ char\ *\ " "ct" ");"
.SH "ARGUMENTS"
.PP
\fIs\fR
.RS 4
The string to be searched
.RE
.PP
\fIct\fR
.RS 4
The characters to search for
.RE
.SH "DESCRIPTION"
.PP
\fBstrsep\fR
updates
\fIs\fR
to point after the token, ready for the next call\&.
.PP
It returns empty tokens, too, behaving exactly like the libc function of that name\&. In fact, it was stolen from glibc2 and de\-fancy\-fied\&. Same semantics, slimmer shape\&. ;)
.SH "COPYRIGHT"
.br
