'\" t
.\"     Title: struct esw1
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: January 2017
.\"    Manual: The ccw bus
.\"    Source: Kernel Hackers Manual 4.10.0-rc1
.\"  Language: English
.\"
.TH "STRUCT ESW1" "9" "January 2017" "Kernel Hackers Manual 4\&.10\&" "The ccw bus"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
struct_esw1 \- Format 1 Extended Status Word (ESW)
.SH "SYNOPSIS"
.sp
.nf
struct esw1 {
  __u8 zero0;
  __u8 lpum;
  __u16 zero16;
  struct erw erw;
  __u32 zeros[3];
};  
.fi
.SH "MEMBERS"
.PP
zero0
.RS 4
reserved zeros
.RE
.PP
lpum
.RS 4
last path used mask
.RE
.PP
zero16
.RS 4
reserved zeros
.RE
.PP
erw
.RS 4
extended report word
.RE
.PP
zeros[3]
.RS 4
three fullwords of zeros
.RE
.SH "AUTHOR"
.PP
\fBCornelia Huck\fR <\&cornelia.huck@de.ibm.com\&>
.RS 4
Author.
.RE
.SH "COPYRIGHT"
.br
