'\" t
.\"     Title: struct skb_shared_hwtstamps
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: January 2017
.\"    Manual: Linux Networking
.\"    Source: Kernel Hackers Manual 4.10.0-rc1
.\"  Language: English
.\"
.TH "STRUCT SKB_SHARED_HW" "9" "January 2017" "Kernel Hackers Manual 4\&.10\&" "Linux Networking"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
struct_skb_shared_hwtstamps \- hardware time stamps
.SH "SYNOPSIS"
.sp
.nf
struct skb_shared_hwtstamps {
  ktime_t hwtstamp;
};  
.fi
.SH "MEMBERS"
.PP
hwtstamp
.RS 4
hardware time stamp transformed into duration since arbitrary point in time
.RE
.SH "DESCRIPTION"
.PP
Software time stamps generated by
\fBktime_get_real\fR
are stored in skb\->tstamp\&.
.PP
hwtstamps can only be compared against other hwtstamps from the same device\&.
.PP
This structure is attached to packets as part of the
skb_shared_info\&. Use
\fBskb_hwtstamps\fR
to get a pointer\&.
.SH "COPYRIGHT"
.br
