'\" t
.\"     Title: struct ciw
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: January 2017
.\"    Manual: The ccw bus
.\"    Source: Kernel Hackers Manual 4.10.0-rc1
.\"  Language: English
.\"
.TH "STRUCT CIW" "9" "January 2017" "Kernel Hackers Manual 4\&.10\&" "The ccw bus"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
struct_ciw \- command information word (CIW) layout
.SH "SYNOPSIS"
.sp
.nf
struct ciw {
  __u32 et:2;
  __u32 reserved:2;
  __u32 ct:4;
  __u32 cmd:8;
  __u32 count:16;
};  
.fi
.SH "MEMBERS"
.PP
et
.RS 4
entry type
.RE
.PP
reserved
.RS 4
reserved bits
.RE
.PP
ct
.RS 4
command type
.RE
.PP
cmd
.RS 4
command code
.RE
.PP
count
.RS 4
command count
.RE
.SH "AUTHOR"
.PP
\fBCornelia Huck\fR <\&cornelia.huck@de.ibm.com\&>
.RS 4
Author.
.RE
.SH "COPYRIGHT"
.br
