'\" t
.\"     Title: struct rio_scan
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: January 2017
.\"    Manual: Internals
.\"    Source: Kernel Hackers Manual 4.10.0-rc1
.\"  Language: English
.\"
.TH "STRUCT RIO_SCAN" "9" "January 2017" "Kernel Hackers Manual 4\&.10\&" "Internals"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
struct_rio_scan \- RIO enumeration and discovery operations
.SH "SYNOPSIS"
.sp
.nf
struct rio_scan {
  struct module * owner;
  int (* enumerate) (struct rio_mport *mport, u32 flags);
  int (* discover) (struct rio_mport *mport, u32 flags);
};  
.fi
.SH "MEMBERS"
.PP
owner
.RS 4
The module owner of this structure
.RE
.PP
enumerate
.RS 4
Callback to perform RapidIO fabric enumeration\&.
.RE
.PP
discover
.RS 4
Callback to perform RapidIO fabric discovery\&.
.RE
.SH "AUTHOR"
.PP
\fBMatt Porter\fR <\&mporter@kernel.crashing.org\&>, <\&mporter@mvista.com\&>
.RS 4
Author.
.RE
.SH "COPYRIGHT"
.br
