'\" t
.\"     Title: svc_print_addr
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: January 2017
.\"    Manual: Linux Networking
.\"    Source: Kernel Hackers Manual 4.10.0-rc1
.\"  Language: English
.\"
.TH "SVC_PRINT_ADDR" "9" "January 2017" "Kernel Hackers Manual 4\&.10\&" "Linux Networking"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
svc_print_addr \- Format rq_addr field for printing
.SH "SYNOPSIS"
.HP \w'char\ *\ svc_print_addr('u
.BI "char * svc_print_addr(struct\ svc_rqst\ *\ " "rqstp" ", char\ *\ " "buf" ", size_t\ " "len" ");"
.SH "ARGUMENTS"
.PP
\fIrqstp\fR
.RS 4
svc_rqst struct containing address to print
.RE
.PP
\fIbuf\fR
.RS 4
target buffer for formatted address
.RE
.PP
\fIlen\fR
.RS 4
length of target buffer
.RE
.SH "COPYRIGHT"
.br
