'\" t
.\"     Title: usb_gadget_probe_driver
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: January 2017
.\"    Manual: Kernel Mode Gadget API
.\"    Source: Kernel Hackers Manual 4.10.0-rc1
.\"  Language: English
.\"
.TH "USB_GADGET_PROBE_DRI" "9" "January 2017" "Kernel Hackers Manual 4\&.10\&" "Kernel Mode Gadget API"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
usb_gadget_probe_driver \- probe a gadget driver
.SH "SYNOPSIS"
.HP \w'int\ usb_gadget_probe_driver('u
.BI "int usb_gadget_probe_driver(struct\ usb_gadget_driver\ *\ " "driver" ");"
.SH "ARGUMENTS"
.PP
\fIdriver\fR
.RS 4
the driver being registered
.RE
.SH "CONTEXT"
.PP
can sleep
.SH "DESCRIPTION"
.PP
Call this in your gadget driver\*(Aqs module initialization function, to tell the underlying usb controller driver about your driver\&. The
\fIbind\fR() function will be called to bind it to a gadget before this registration call returns\&. It\*(Aqs expected that the
\fIbind\fR() function will be in init sections\&.
.SH "AUTHOR"
.PP
\fBDavid Brownell\fR <\&dbrownell@users.sourceforge.net\&>
.RS 4
Author.
.RE
.SH "COPYRIGHT"
.br
