'\" t
.\"     Title: w1_remove_master_device
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: January 2017
.\"    Manual: W1 API internal to the kernel
.\"    Source: Kernel Hackers Manual 4.10.0-rc1
.\"  Language: English
.\"
.TH "W1_REMOVE_MASTER_DEV" "9" "January 2017" "Kernel Hackers Manual 4\&.10\&" "W1 API internal to the kernel"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
w1_remove_master_device \- unregister a master device
.SH "SYNOPSIS"
.HP \w'void\ w1_remove_master_device('u
.BI "void w1_remove_master_device(struct\ w1_bus_master\ *\ " "bm" ");"
.SH "ARGUMENTS"
.PP
\fIbm\fR
.RS 4
master bus device to remove
.RE
.SH "AUTHOR"
.PP
\fBDavid Fries\fR <\&David@Fries.net\&>
.RS 4
Author.
.RE
.SH "COPYRIGHT"
.br
