'\" t
.\"     Title: write_one_page
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: January 2017
.\"    Manual: Memory Management in Linux
.\"    Source: Kernel Hackers Manual 4.10.0-rc1
.\"  Language: English
.\"
.TH "WRITE_ONE_PAGE" "9" "January 2017" "Kernel Hackers Manual 4\&.10\&" "Memory Management in Linux"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
write_one_page \- write out a single page and optionally wait on I/O
.SH "SYNOPSIS"
.HP \w'int\ write_one_page('u
.BI "int write_one_page(struct\ page\ *\ " "page" ", int\ " "wait" ");"
.SH "ARGUMENTS"
.PP
\fIpage\fR
.RS 4
the page to write
.RE
.PP
\fIwait\fR
.RS 4
if true, wait on writeout
.RE
.SH "DESCRIPTION"
.PP
The page must be locked by the caller and will be unlocked upon return\&.
.PP
\fBwrite_one_page\fR
returns a negative error code if I/O failed\&.
.SH "COPYRIGHT"
.br
